package com.example.infs3605;

import java.util.ArrayList;

public class Art {
    public Art(String artId, String artTitle, String artIdentifier, String artType, String artDate, String artRegion, String artCreator, String artPhysicalDescription) {
        this.artId = artId;
        this.artTitle = artTitle;
        this.artIdentifier = artIdentifier;
        this.artType = artType;
        this.artDate = artDate;
        this.artRegion = artRegion;
        this.artCreator = artCreator;
        this.artPhysicalDescription = artPhysicalDescription;
    }

    private String artId;
    private String artTitle;
    private String artIdentifier;
    private String artType;
    private String artDate;
    private String artRegion;
    private String artCreator;
    private String artPhysicalDescription;

    public String getArtId() {
        return artId;
    }

    public void setArtId(String artId) {
        this.artId = artId;
    }

    public String getArtTitle() {
        return artTitle;
    }

    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle;
    }

    public String getArtIdentifier() {
        return artIdentifier;
    }

    public void setArtIdentifier(String artIdentifier) {
        this.artIdentifier = artIdentifier;
    }

    public String getArtType() {
        return artType;
    }

    public void setArtType(String artType) {
        this.artType = artType;
    }

    public String getArtDate() {
        return artDate;
    }

    public void setArtDate(String artDate) {
        this.artDate = artDate;
    }

    public String getArtRegion() {
        return artRegion;
    }

    public void setArtRegion(String artRegion) {
        this.artRegion = artRegion;
    }

    public String getArtCreator() {
        return artCreator;
    }

    public void setArtCreator(String artCreator) {
        this.artCreator = artCreator;
    }

    public String getArtPhysicalDescription() {
        return artPhysicalDescription;
    }

    public void setArtPhysicalDescription(String artPhysicalDescription) {
        this.artPhysicalDescription = artPhysicalDescription;
    }

    public static ArrayList<Art> getArtworks() {
        ArrayList<Art> artworks = new ArrayList<>();
        artworks.add(new Art("1", "Carved wooden goanna with pokerwork design", "60/078/IR_4528.0087", "Wood carvings", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A carved wooden goanna. The goanna is carved from solid form with it's tail and body in a straight line. The head and tail both taper to a point. The goanna has four legs and is decorated with a pokerwork design. On the underneath handwritten in black ink is \"38 / 7-0474\"."));
        artworks.add(new Art("2", "Carved wooden bird with pokerwork design", "60/079/IR_4528.0088", "Wood carvings", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A carved wooden bird. The bird is carved from a solid form with its head and tail in a straight line. The legs are forked, protruding from beneath the body and forming the base. The body is flat with a curved surface. The tail extends upwards. The head is slightly bend to one side. The bird is decorated with a pokerwork design. On the underside handwritten in black ink is \"25 / 7-0462\"."));
        artworks.add(new Art("3",  "Bag with long stitch design", "60/083/IR_4528.0092", "Bags", "Unknown", "Sydney, New South Wales, Australia", "Unknown", "A bag with long stitch decoration. The bag consists of two rectangular panels of white fabric sewn together on three sides. On one of the panels is a long stitched design featuring blue lines forming diamond shapes with pink long stitched patterns in the middle. Above the design are pink long stitched crosses and circles. Below the design is a pink motif. Attached to either side of the opening is a long and narrow rectangular length of fabric to form the strap. Attached to the strap with pink cotton tape is a yellow stick it not folded in half with the number \"z0102\". Cotton threads have been sewn to the bottom of the bag on the left and right hands sides."));
        artworks.add(new Art("4", "Wooden smoking pipe with a pigmented design", "60/084/IR_4528.0093", "Smoking pipes", "Unknown","Sydney, New South Wales, Australia", "Unknown", "A wooden smoking pipe. The pipe is cylindrical in shape, tapering slightly at either end. The centre of the pipe is hollowed out at one end. At the other end is attached a hollow cylindrical piece of metal. The pipe is pigmented brown and yellow with bands of white, yellow and brown cross hatchings. Attached to either end of the pipe is a piece of yellow blue tack."));
        artworks.add(new Art("5", "Wooden container with a painted design depicting a bird flying over a landscape", "60/097/IR_4528.0106", "Containers", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A carved wooden coolamon. The coolamon is narrow and curved with rounded sides. The surface is pigmented brown with a bird and landscape design on the exterior. The bird is white with black outlines and dot patterning. The landscape consists of a river and trees. Attached to the interior surface is a white sticker with black handwritten text \"018/05\"."));
        artworks.add(new Art("6", "Wooden shield with pokerwork design", "60/100/IR_4528.0109", "Shields", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A carved wooden shield. The shield is carved from solid form, is oval in shape with a handle carved into the centre of the posterior surface. On the handle are two stickers, one a bar code sticker with the numbers \"A0000145\", and the other a red and silver sticker with the text \"PROPERTY OF / ATSIC / CRO\" and the asset number \"00144\". The anterior surface is decorated with etchings and pokerwork design featuring snakes, and landscape panels with birds and kangaroos."));
        artworks.add(new Art("7", "Carving of a turtle", "60/101/IR_4528.0110", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Nawurapu Wunungmurra", "A wooden carving from one piece of cylindrical wood featuring a turtle with a long neck opposite a piece of wood. The turtle is pigmented black with the shell decorated with diamond and cross hatch design in brown, yellow and white. On the other side of the turtle on the piece of wood is the same diamond and cross hatch patterns. Underneath the base is handwritten text that reads 'C-5735', and a silver ATSIC sticker with the same number."));
        artworks.add(new Art("8", "Beaded necklace strung with seeds", "60/102/IR_4528.0111", "Necklaces", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A beaded necklace. The necklace is made from seeds strung together on a thread. The seeds are oval in shaped with a reddish brown colouring."));
        artworks.add(new Art("9", "Necklace strung with small seed pods", "60/103/IR_4528.0112", "Necklaces", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A necklace. The necklace is made from small seed pods strung together on a blue cotton thread. The pods are hollow and shaped like small bowls. The pods are strung together based to head slightly overlapping each other."));
        artworks.add(new Art("10", "Wooden carving of an unknown animal", "60/106/IR_4528.0115", "Wood carvings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A wooden carving of an animal. The animal is carved from light coloured wood, is round in shape with four legs and a broad tail tapering to a point. The head of the animal tapers downwards. The animal is decorated with a pokerwork design."));
        artworks.add(new Art("11", "Wooden carving of four birds on a branch with pokerwork design", "60/108/IR_4528.0117", "Wood carvings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "The birds and branch are carved from a solid form. The branch is straight and narrow with rounded ends. The birds have oval shaped bodies with elongated necks and rounded heads tapering to the beak. Pairs of birds are positioned on either end of the branch facing each other but with their heads slightly turned in an opposing direction. The birds have been decorated with a pokerwork design."));
        artworks.add(new Art("12", "Didjeridu with burned design of animals", "60/112/IR_4528.0121", "Didjeridu", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A didjeridu with a burned design of a kangaroo, bird and an emu. The animal motifs are filled in with linear and curved designs and outlined with dots. Both the ends are painted black with rows of dots in white, one end also has more rows of dots in red, brown and yellow. There is a label adhered to the didjeridu which has the text \"EO10\"."));
        artworks.add(new Art("13", "Bird", "60/115/IR_4528.0124", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A carved wooden bird. The bird is carved from solid form standing upright on a circular base. The base tapers into the legs of the bird. The body is cylindrical with the tail tapering downwards adjacent to the base. The bird has a long neck that curves over at the head. The head is rounded, has a crest and tapers to the beak which reaches to the body. The bird is pigmented black, with brown, white and yellow cross hatched patterns on the body and tail. The base is pigmented brown. On the underside of the base is a sticker from the 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION' with the ATSIC asset number 'C-5736'. Also on the base handwritten in blue ink is 'C-5736 / ATSIC'."));
        artworks.add(new Art("14", "Carved Shield", "60/116/IR_4528.0125", "Shields", "Unknown", "Kununurra, Kimberley, Western Australia, Australia", "Unknown", "A shield pigmented black carved in an oval with a convex back and flat front surface. A handle has been cut into the convex back. A carved fine zigzag line is used to create designs of lines, diamonds, semicircles and leaf-type shapes. There are also two bird motifs on the front surface. A picture hook has been screwed into the front surface and a loop of metal wire attached. There is a sticky label attached to the front surface with text that reads \"KNA - 04\"."));
        artworks.add(new Art("15", "Hollow log with painted decoration", "60/117/IR_4528.0126", "Ceremonial objects", "Unknown", "Brisbane, Queensland, Australia", "Unknown", "A hollow log pigmented on the outside featuring birds and goannas on a brown background with black, yellow and white lines and cross hatching separated by black lines with yellow and white dots. The ends of the log are split. There is a piece of paper at on end that reads \"No: 39\"."));
        artworks.add(new Art("16", "Fibre broom", "60/118/IR_4528.0127", "Brooms", "Unknown", "Brisbane, Queensland, Australia", "Unknown", "A broom featuring long thin straight fibres gathered together. At one end the fibres are platted and spiral around the gathered fibres. The is a tag attached to platted fibres that reads \"No. 42\"."));
        artworks.add(new Art("17", "Carved figure with miniature spear and spearthrower", "62/227/rg_62227", "Wood carvings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Unknown", "A carved human figure with spear and spearthrower. There is black hair attached to the head and the figure is pigmented with brown, white and black colours."));
        artworks.add(new Art("18", "Carved wooden shield", "60/124/IR_4528.0131", "Shields", "Unknown", "Derby, Western Australia, Australia", "Unknown", "A carved and painted wooden shield. The shield is an elongated oval shape with a raised inset handle in the centre on one side. The side with the handle has been incised with a design of leaves, kangaroos, birds and a snake with a textured surface, picked out in yellow over a brown background. The other side of the shield is similarly incised with a design that features a snake surrounded by scalloped shapes. The edges of the shield are worn and chipped in places."));
        artworks.add(new Art("19", "Carving of a female figure with grass skirt", "60/125/IR_4528.0132", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Jack K. Kaiwulan", "A wooden carving featuring a female figure with her head facing to the left. The figure is pigmented in black, with brown lines and white dot details on the face and chest. The figure is wearing a brown grass skirt and is standing on a brown base which is oval shaped with pointed ends. ATSIC 'Asset No: C - 0683'."));
        artworks.add(new Art("20", "Carving of a snake on a log", "60/126/IR_4528.0133", "Wood carvings", "Unknown", "Bourke, New South Wales, Australia", "Unknown", "A carved wooden snake wrapped around a wooden stick. The stick has a rough texture with yellow and red smudging covered by white and yellow designs. The snake is covered with black paint and has designs of spots and lines on the upper section."));
        artworks.add(new Art("21", "Model bark canoe", "60/127/IR_4528.0134", "Small scale models", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A model canoe made of painted bark and grass twine. The canoe is made of a single sheet of bark folded over and sewn with twine. Each end narrows into a rounded point. The exterior of the canoe is painted in stripes and dots of white, yellow and red brown. The paint is worn in places."));
        artworks.add(new Art("22", "Rug with decorative pattern", "60/129/IR_4528.0136", "Rugs", "Unknown", "Adelaide, South Australia, Australia", "Nyukana (Daisy) Baker", "A rectangular shaped rug featuring woollen strands woven together with a white cotton backing. The rug is brown with orange, red, yellow and white wavy designs surrounding a central concentric circle."));
        artworks.add(new Art("23", "Spearthrower", "60/130/IR_4528.0137", "Spearthrowers", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden spear thrower with curved sides that taper to a thin end with carved rounded handle. There is orange sting wrapped around the handle. At the other end is a sharpened wooden peg which is attached with natural sting fibres which is coming loose."));
        artworks.add(new Art("24", "Boomerang", "60/131/IR_4528.0138", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "An asymmetrical boomerang featuring one piece of wood with a large crack from the middle to the short arm end. There has been a whole piece broken off the inner middle which has been glued bak in place."));
        artworks.add(new Art("25", "Boomerang with kangaroo pokerwork", "60/132/IR_4528.0139", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang with pokerwork featuring a kangaroo or wallaby with grass either side and three black bands at either end. On the other side is pokerwork initials which reads \"MM / Carr River\". There is also hand written text that reads \"AF119\" and a white sticker that reads \"LILLIE - PILLIE\"."));
        artworks.add(new Art("26", "Boomerang featuring a Koala design", "60/133/IR_4528.0140", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang with pokerwork featuring a koala in a tree with grass either side. There are four plain bands and two bands with lines at each end. On the flat side is pokerwork text that reads \"MM\". There is also handwritten text that reads \"AF118\" and two stickers."));
        artworks.add(new Art("27", "Boomerang painted with grub design", "60/139/IR_4528.0146", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented red-brown with three black circles, each with a white grub with red head pictured inside the circle. The background is filled with white, black, yellow and red dots. On the flat side is pokerwork that reads \"WEMBA / WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 3 of 4\"."));
        artworks.add(new Art("28", "Boomerang painted with black oval design", "60/140/IR_4528.0147", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented red-brown with black ovals and circles surrounded by white, yellow, red and black dots and is varnished. On the flat side is pokerwork that reads \"WEMBA WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 4 of 4\"."));
        artworks.add(new Art("29", "Boomerang with five concentric circle dot designs", "60/141/IR_4528.0148", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented with brown ends and black middle with a dot design featuring five concentric circles painted with white, yellow and brown dots. On the flat side is pokerwork that reads \"WEMBA WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 2 of 4\"."));
        artworks.add(new Art("30", "Carved wooden spearthrower", "60/142/IR_4528.0149", "Spearthrowers", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A carved wooden spear thrower. The spear thrower is long and curved. It tapers to a point at one end and has a carved handle at the other. The handle is oval is shape. At each end is coiled a piece of wire. The spear thrower has been damaged with a section of the wood broken off on one side and reattached with clear tape. On the exterior surface is a silver sticker from the \"ABORIGINAL DEVELOPMENT / COMMISSION\" with the ADC asset number \"5 0205\"."));
        artworks.add(new Art("31", "Coiled woven shallow basket with hanging hook", "60/143/IR_4528.0150", "Baskets", "Unknown", "Adelaide, South Australia, Australia", "Ellen Trevorrow", "A coiled woven basket. The basket is made from grass using a coiled basketry technique. The basket is shallow and circular with a wide flat base and straight sides. Attached to the exterior of the base is a triangle hanging hook."));
        artworks.add(new Art("32", "Ceramic urn decorated with six grey figures", "60/144/IR_4528.0151", "Urns", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A ceramic urn. The urn is cylindrical and tapers to a flat base. The top of the urn tapers to a rounded lip. The urn has a brown red colouring and it decorated with six grey figures that are smooth to touch. On the base is a signature."));
        artworks.add(new Art("33", "Woven fish scoop - coiled woven cone shaped basket with hanging hook", "60/145/IR_4528.0152", "Fish traps", "Unknown", "Adelaide, South Australia, Australia", "Ellen Trevorrow", "Woven fish scoop, made from rushes (Cyperus spp.) using a type of coiled basketry technique. The scoop is constructed by curling a circular matt at one end to form a cone shape. The curled edges have been intertwined with the weave to secure them together. Attached to one of the sides is a triangular hanging hook."));
        artworks.add(new Art("34", "Dancing headdress", "60/147/IR_4528.0154", "Headdresses", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A conical headdress made of bark with the exterior wrapped in handmade twine in browns with a painted decoration of a vertical stripe of red surrounded by two vertical stripes of white. The tip of the cone has a cylindrical piece of wood inserted into it, wrapped in white-painted twine and with a tassel of natural coloured feathers at the very top."));
        artworks.add(new Art("35", "Mimi spirits and Namarodo spirits", "60/148/IR_4528.0155", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Thompson Ngainmirra", "A colour bark painting featuring an x-ray kangaroo with a goanna at the top and a linear figure and two spears at the bottom. The bark is pigmented brown with white line and cross hatch detail. At the top and bottom are cylindrical wooden sticks bound to the bark with natural fibres though holes. On the reverse is a wooden block and two pieces of paper, one of which starts with \"ARTIST: THOMPSON NGAINMIRRA / ....\". There is also a silver sticker which has been crossed out."));
        artworks.add(new Art("36", "Bark painting featuring two fish", "60/149/IR_4528.0156", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Nguleingulei Muramura", "A colour bark painting featuring two fish, the top one with fins, pigmented brown with rectangular patches of white and orange brown dots. The bark is pigmented with a black background with brown border. The ends of the bark are clamped with two pieced of wood that are bound with sting at the ends."));
        artworks.add(new Art("37", "Bark painting depicting two water goannas", "60/150/IR_4528.0157", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Nguleingulei Muramura", "A colour bark painting featuring two x-ray goanna pigmented white with brown line patterns on a brown background. The ends of the bark cylindrical pieces of wood bound with string through four holes. On the reverse of the bark is the number \"79\" and a piece of paper some of which reads \"Two water Goannas - burral / by Dick Ngulayngulay / Murumuru...\""));
        artworks.add(new Art("38", "Painting of two crabs", "60/166/IR_4528.0173", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Gnowerran", "A colour painting on bark featuring two brown crabs. The crabs are multicoloured with cross hatched line markings on their backs. The crabs are facing each other and divided by a yellow band patterned with brown and yellow dots. Within the yellow band are two brown circular shapes outlined and with yellow line markings. The background consists of black, white and brown cross hatchings. On the bottom right corner is a signature \"GNOWERAN\". The painting is under glass with a black metal frame."));
        artworks.add(new Art("39", "Wooden container with dot painting on the rounded side mounted and framed", "60/153/IR_4528.0160", "Containers", "Unknown", "Adelaide, South Australia, Australia", "Molly Nungurrayi", "A painted wooden coolamon featuring three brown concentric circles surrounded by brown half circles with white dots. The background is black filled with grey, yellow and red dot patches. The coolamon is block mounted to a hessian board and framed with a wooden frame. The back of the frame has a white piece of paper that reads \"Artist: Molly Nungurrayi / Tribe: Warlpiri / Site: Yarrankanyi / Womens Dreaming / ...\". There is also two stickers one reads \"ABORIGINAL DEVELOPMENT / COMMISSION / \" 5 0345\"."));
        artworks.add(new Art("40", "Landscape painting with black ink", "60/167/IR_4528.0174", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Robert Eggington", "An black ink painting on paper of a landscape. There are two leafless trees one on the left and one on the right with their shadow falling to the left. In the background are smaller leafless trees with a dark patch of trees and shrubs across the middle with the bottom edges bleeding. There are eleven small birds in the sky and the foreground is filed with a wash technique."));
        artworks.add(new Art("41", "Dot painting of a snake surrounding a concentric circle", "60/168/IR_4528.0175", "Paintings", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A colour dot painting on canvas featuring a snake. The snake is circling anti-clockwise towards a series of brown concentric circles at the centre of the painting. The snake is patterned with yellow, white and black dots and outlined by white dots. The background is black with brown dots and yellow dot flowers with white centres. The painting is stretched over a strainer and stapled to the back."));
        artworks.add(new Art("42", "Dot painting of three platypus", "60/177/IR_4528.0184", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "A Sparrow", "A colour dot painting on canvas featuring three platypus painted in black with white and yellow markings on a brown background of yellow, white, red and varying browns dot coloured lines. A signature on the bottom right reads 'A. SPARROW'. On the reverse side printed text reads 'Fredrix /... / Quality Artists Canvas Panel / ...'."));
        artworks.add(new Art("43", "Dot painting of two artefacts", "60/179/IR_4528.0186", "Paintings", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A brown and yellow dot painting on canvas board featuring stylised pictures two artefacts, one shaped like a large oblong and the other a narrow figure with blunt pointed ends. The painting is under glass and has a white matt with a brown wooden frame."));
        artworks.add(new Art("44", "Painting of two emus within a circle", "60/181/IR_4528.0188", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "Mr Mark J. Knight", "A colour painting on board displaying an x-ray design of the skeletal and digestive features of two emus enclosed within a black circle outlined with brown dots and with a series of emu footprints circling clockwise on the inner rim of the circle. On the reverse is the name of the artist \"Mark John Knight\" and the paintings title \"Emus\". The painting has a gold and brown wooden frame."));
        artworks.add(new Art("45", "Dot painting of an x-ray kangaroo", "60/182/IR_4528.0189", "Paintings", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A colour dot painting on canvas board featuring an x-ray design of a kangaroo looking to its back and surrounded by a serious of different coloured dot patterns and animal footprints. The painting is under glass and has a white matt with a brown wooden frame."));
        artworks.add(new Art("46", "Painting of a man sitting holding flowers with a background of dot painting", "60/184/IR_4528.0191", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A painting on wood of an indigenous man holding flowers sitting on the sand. The image of the man is surrounded by a dot design with four concentric circles in the corners. The dots are painted in white, off white, yellow and pink. There is a white sticker on the frame with text \"ATSIC P.A 9000194\". On the reverse is hand written initials \"B.D\". The painting is framed by a wooden frame painted black."));
        artworks.add(new Art("47", "Another Story", "60/191/IR_4528.0198", "Prints", "Unknown", "Perth, Western Australia, Australia", "Sally Morgan", "A colour print on paper featuring many black figures below a house with a picket fence. The print is titled 'Another Story'', and signed 'Sally Morgan' with the edition number 84/95'."));
        artworks.add(new Art("48", "Narlgu Dreaming", "60/193/IR_4528.0200", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Alan Egan", "A coloured dot painting on canvas board displaying an arrangement of different features including concentric circles, curving lines and thin narrow rods with pointed ends all forming a rectangular boarder around a large central feature that is outlined in white dots and then reproduced to form the cream, yellow, green, and brown dotted line patterns in the background. On the reverse is the artists name \"ALAN EGAN\", the title \"NARLGU DREAMING\" and handwritten text \"Gascoy[n?]e Yamatji / Alan. Egan\" with the ATSIC asset number \"CA-8\". The canvas is stretch over a wooden strainer and has a brown wooden frame."));
        artworks.add(new Art("49", "Dot painting with central concentric circles and wavy yellow dot lines", "60/194/IR_4528.0201", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Long Jack Phillipus Tjakamarra", "A coloured dot painting on black canvas board featuring a series of yellow and brown dotted curving lines, some with white tuffs on their ends, amongst a background of varying coloured dot patterned areas with brown dot feature patterns running diagonally from each corner to the yellow and brown dotted concentric circles in the centre. On the reverse is handwritten in pencil 'Phyllis'. The canvas is stretched over a wooden strainer and stapled to the edges."));
        artworks.add(new Art("50", "Painting of a crocodile and fish around a circle", "60/198/IR_4528.0205", "Paintings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Ngalawurr", "A painting on canvas board of a central circle surrounded by a crocodile and a fish. There is a cross hatched background in brown, yellow, black and white. The painting is signed \"Ngalawurr\". The painting is unframed."));
        artworks.add(new Art("51", "Painting featuring four figures sitting in the grass", "60/203/IR_4528.0210", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "M Palmer", "An oil painting on canvas board featuring four indigenous men sitting on the ground the one on the left holding a white object and pointing to the ground. There is a wooden pole painted on the right of the painting and a bush with yellow flowers on the left. There are two stamps on the back. The painting is framed in a wooden frame."));
        artworks.add(new Art("52", "Bark painting of a Kangaroo", "60/204/IR_4528.0211", "Bark paintings", "Unknown", "Perth, Western Australia, Australia", "Mijau Mijau", "A colour painting on bark featuring a brown kangaroo vertically positioned with white cross hatched line markings on it's face, legs and stomach and straight line markings elsewhere. On the reverse of the painting in black handwritten ink is \"Mijau Mijau\" and a label that reads \"DREAMING TIME KANGAROO. JIRITJA MOIETY. / Painted by Mijau-Mijau. / Croker Island.\""));
        artworks.add(new Art("53", "Brolga Life", "60/205/IR_4528.0212", "Print", "Unknown", "Townsville, Queensland, Australia", "Joseph A. Cummins", "A black print on white paper featuring a central bird like image with white line markings emerging from the bottom and surrounded by various animal such as a crocodile, turtles, fish, frogs, other birds and insects, with two human figures to the left and scattered vegetation throughout. At the bottom is the series number \"2/50\", the title \"BROLGA LIFE AROUND WATER HOLE\" and the artists name \"Joseph. A. Cummins\". The print is under perspex, has a black matt and a dark brown wooden frame."));
        artworks.add(new Art("54", "Landscape painting of mountains and grass trees", "60/210/IR_4528.0217", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Unknown", "A painting on board featuring three mountains in the background with two birds flying in the orange and pink sky above. In the landscape below is an emu in the middle foreground with a grass tree to its left and another grass tree to the far right. There are also two leafless trees on the left side and three on the right The painting is under glass with a black mat and wooden frame with gold inner edge."));
        artworks.add(new Art("55", "Painting of a snake with nine black circles and two hand prints", "60/211/IR_4528.0218", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Anthony D. Chambers", "A painting on canvas board featuring a snake wrapped around nine black circles. There are two black hand prints in the bottom left and right corners with blown paint in red, white, and yellow around the outside of the hands. The background is made up of segments of white, red and yellow dots and around the outside of the snake is red, yellow line and smaller red dots. On the back is hand written text that reads \"3MIN\". The painting is framed in wooden frame"));
        artworks.add(new Art("56", "Northern Quolls", "60/212/IR_4528.0219", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Chrisa Bojack", "A painting on paper featuring two quolls on branches with green leaves. The quolls are brown with white spots and the background consists of splattered paint in brown, yellow and black. In the bottom left corner is painted text that reads \"NORTHERN QUOLLS\". There is nothing on the reverse. The painting is under glass mounted to a green backing board and has a wooden frame painted black. There is a white card sticky taped to the glass with hand written text that reads \"ARTIST: Chriss Bojack\"."));
        artworks.add(new Art("57", "Untitled landscape painting", "60/214/IR_4528.0221", "Paintings", "Unknown", "Perth, Western Australia, Australia", "M Turner", "A colour landscape painting on board featuring a body of water and a white and brown barked leafless tree. The body of water is surrounded by red rocky outcrops and leafy vegetation. The leafless tree has birds sitting in it's branches. The background consists of a blue sky scattered with white fluffy clouds. An unrecognisable signature is in the bottom right corner. On the reverse is text handwritten in pencil \"Turner. M.\", with a white marker \"DAA CA1\" and the number \"CPA1\" is stuck to the side. The painting has a silver wooden frame with gold trim."));
        artworks.add(new Art("58", "Painting of leafless trees on a salt flat", "60/215/IR_4528.0222", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Lance Tjyllyungoo", "A watercolour painting on paper featuring numerous leafless trees in a black and white barren landscape. Shadows from the trees fall to the bottom left of the picture. A signature 'TTyllyungoo' appears at the bottom right corner."));
        artworks.add(new Art("59", "Painting of trees on a salt flat", "60/216/IR_4528.0223", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Lance Tjyllyungoo", "A painting on paper featuring two trees in the foreground on a salt flat. There is a row of dark dense trees in the background and light washed sky with dark clouds at the top. The painting is signed in the bottom right corner."));
        artworks.add(new Art("60", "Poster with image 'Kemarre's Identity'", "60/219/IR_4528.0226", "Posters", "Unknown", "Ceduna, South Australia, Australia", "Heather S. Kemarre", "A colour dot poster on paper featuring three circles compose by white dot concentric rings and joined to each other by three parallel white dot lines all surrounded by brown horseshoe shapes with grey dot outlines, and numerous shapes in two horizontal lines, made up of brown and red lines and outlined in white dots on a background of red and brown dots patterns. At the bottom of the poster is text 'KEMARRE'S IDENTITY / This shows the community of Mbantua... ARTIST: HEATHER KEMARRE SHEARER.'. The poster is under glass has a cream coloured matt with red and black edging and a black wooden frame."));
        artworks.add(new Art("61", "Dot painting", "60/220/IR_4528.0227", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A dot painting on canvas featuring three concentric circles horizontally across the middle, there are half circles surrounding them painted purple. There are five brown figures along the bottom and six brown figures along the top. The background is black with green, yellow and purple dots. There are two stickers on the back one reads \"PROPERTY OF / ATSIC / CRO / 00182\". The painting is under glass with white mat and wooden frame painted green / blue with white ridges."));
        artworks.add(new Art("62", "Poster titled 'Ngaanyatjarra Council'", "60/223/IR_4528.0230", "Posters", "Unknown", "Perth, Western Australia, Australia", "Unknown", "A colour poster featuring a reproduction of poker work design of concentric circles and overlapping of concentric circles. There is text at the bottom that reads 'NGAANYATjARRA / COUNCIL'. There are damage marks on the sides just over the middle."));
        artworks.add(new Art("63", "Painting of a portrait and snake with four concentric circles", "60/225/IR_4528.0232", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A colour painting on black canvas board featuring the face of a bearded indigenous man wearing a red headband with a yellow, red, white, and blue dot patterned snake in the background and concentric dot circles in each of the corners. The painting has a brown wooden frame."));
        artworks.add(new Art("64", "Photograph of five men, three holding weapons", "60/229/IR_4528.0236", "Photographic prints", "Unknown", "Townsville, Queensland, Australia", "Unknown", "An enlarged reproduction of a black and white photograph, depicting five seated indigenous men. One holds a spear, one holds a boomerang and one holds and elongated object on the left hand side. On the back is a blue circular sticker on the bottom left hand side with the number \"42\". The reproduction is mounted to a backing board painted black."));
        artworks.add(new Art("65", "Landscape painting featuring a dirt road", "60/233/IR_4528.0240", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Greg Kelly", "A painting of a dirt road with large trees either side and mountains in the background. There is a bright yellow and orange desert with green grass in the foreground and expansive sky with scattered clouds. The painting is signed by \"GREG KELLY\" in the bottom left corner. On the back there is a sticker in the top left corner with \"RA - 47\", and hand written text with \"BA17 /...\". The painting is framed in a wooden frame."));
        artworks.add(new Art("66", "Painted boomerang", "60/235/IR_4528.0242", "Boomerangs", "Unknown", "Ceduna, South Australia, Australia", "Maureen Nampajinpa", "A symmetrical wooden boomerang with a painted surface featuring a dot design with yellow footprints, a pink and purple snake and two concentric dot circles. The boomerang is mounted on a black backing board but has dislodge and slipped down on the left side. On the reverse is handwritten text \"Maureen Nampajinpa / Hudson\" and the ATSIC bar code number \"A0000137\". The boomerang is under glass and has a brown matt with a brown wooden frame."));
        artworks.add(new Art("67", "Two posters of artwork", "60/243/IR_4528.0250", "Posters", "Unknown", "Ceduna, South Australia, Australia", "Heather S. Kemarre", "Two coloured posters showing printed reproductions of paintings by Heather Shearer Kemarre. One poster is titled 'ARANDA DREAMING FOR TJARPE' and shows an earth coloured scene of eight slug-like shapes pointing towards the centre of the work where there are brown and white dotted circles. The other posters is titled 'WOMEN'S DREAMING FOR YERAMPE' and shows a red and brown scene of black and red insects surrounding a cross-like design outlined in white dots and a brown border. Brown and white dotted circles sit within the cross design. Both posters have the artist signature 'H.SHEARER' visibile in the bottom right corner of the work, as well as production information printed at the bottom which includes 'Printed by Concord Printing Pty. Ltd'."));
        artworks.add(new Art("68", "Silk painting of two lizards", "60/244/IR_4528.0251", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Josie Davey", "A colour painting on silk featuring two lizards, two boomerang shaped objects and a snake on an off white background with yellow and brown arc patterns. The artists signature \"Josie Davey\" is in the bottom right corner. The painting is under glass and has a yellow matt with a black wooden frame."));
        artworks.add(new Art("69", "Painting of fish", "60/245/IR_4528.0252", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour painting on canvas board featuring a school of grey fish facing to the left with a blue background. The artist signature \"G. HASELDINE\" is in the bottom right corner. On the reverse is stuck a guarantee from \"TIMBER CREEK / PICTURE FRAMING\". The painting is under glass, has a grey matt and a washed blue wooden frame."));
        artworks.add(new Art("70", "Painting of a crocodile, snakes and a figure", "60/247/IR_4528.0254", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "F E. Carlo", "A brown, white and yellow painting on canvas with a black background featuring two figures on either side of a crocodile and a snake circling from bottom to top on the left side. The signature 'E.CARLO' is in the bottom right corner. The canvas is stretched onto a wooden stretcher."));
        artworks.add(new Art("71", "Aboriginal Bush food", "60/248/IR_4528.0255", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour painting on canvas board featuring four goannas and two lizards surrounded by red, green, and orange berry like objects and white witchetty grub like animals. On the reverse it the title \"Aboriginal Bush Food\" and the artists name \"GLETYS. E. HASELDINE.\" The painting has a red metal frame."));
        artworks.add(new Art("72", "Mimi, A Married Man", "60/250/IR_4528.0257", "Prints", "Unknown", "Ceduna, South Australia, Australia", "Paddy F. Wainburranga", "A print on paper of a stylised indigenous figure holding two painted sticks with birds and snakes surrounding it. The print is in brown, yellow, black colours with dot details. There is a black boarder with dots surrounding the central images. The edition number is 40/99 and has written text 'PADDY.RDAM.' at the bottom."));
        artworks.add(new Art("73", "Painting of a crocodile and bird with waterlilies", "60/251/IR_4528.0258", "Paintings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Bronwyn Wuyuwa Gellet", "A painting on canvas board of a crocodile and a bird with a central flower like design. There are two flowers in the bottom left and the top right corners of the painting, with dot painting in the lower half and cross hatch painting in the upper half. Colours used include grey, green, pink and yellow with a distinctive red boarder. The painting is framed in a wooden frame painted grey."));
        artworks.add(new Art("74", "Dugong", "60/259/IR_4528.0266", "Bark paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Bede Tungatalum", "A painting on material/cloth featuring five dugongs. Four of the dugongs are white and the fifth is black. All the dugongs are patterned with line markings. The background consists of a line patterned. On the reverse is a silver sticker from the 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION' with the ATSIC asset number 'C-0981'. The canvas is stretch over a strainer and attached to a black backing board. Attached to the top of the backing board with cotton tape is a black label with white text 'Dugong / Bebe Tungatalum b1852 / ?'. The label is in a clear plastic zip lock bag."));
        artworks.add(new Art("75", "Dot painting", "60/260/IR_4528.0267", "Paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Leonora Napparulla", "A colour dot painting on canvas featuring a pattern of concentric circles, and half circle shapes. In the centre are brown concentric circles with half circles around the outside circle. The top and bottom of the middle circles are circles consisting of small half circle shapes. To the left and right of the middle circle are circles consisting of large half circle shapes. On the reverse handwritten in black ink \"C-1701 / FRAME 357\". Also on the reverse is a silver sticker from the \"ABORIGINAL AND TORRES STRAIT / INSLANDER COMMISSION\" with the ATSIC asset number \"C-1701\". Attached the reverse with brown tape is a black label with white text \"Title unknown / Leonora Napparulla / ...\". The canvas is stretched over a strainer, has a backing board and a brown wooden frame."));
        artworks.add(new Art("76", "Four kangaroos and an echidna", "60/267/IR_4528.0274", "Bark paintings", "Unknown", "Sydney, New South Wales, Australia", "Djawida Nadjongorle", "A colour painting on bark featuring four kangaroos and an echidna depicted in an X-ray cross hatch design. The echidna is positioned at the bottom of the painting with the four kangaroos positioned one above the other above it. The cross hatch design is in black, white, yellow and red stripes. Wooden sticks are attached to the top and bottom of the bark with string. On the reverse handwritten in black ink is 'OE.103 / ARTRED / 5/201'. Also on the reverse is adhered a piece of white paper with the text 'OENPELLI BARK PAINTINGS / ... / ARTIST DJAWIDA / ...'. In the top left corner of the paper is a silver sticker from the 'ABORIGINAL DEVELOPMENT / COMMISSION' with the number '2 0574'."));
        artworks.add(new Art("77", "Kangaroo", "60/269/IR_4528.0276", "Bark paintings", "Unknown", "Sydney, New South Wales, Australia", "Jimmy Kalarriya Namarnyilk", "A colour painting on bark featuring a kangaroo with a white and brown cross hatch pattern on it's tail, hind legs, forearms and face. The kangaroo is positioned vertically with it's hind legs up against it's chest. Wooden sticks are attached to the top and bottom of the bark by string. On the reverse is attached a discoloured white piece of paper with black text under the title \"OENPELLI BARK PAINTINGS\" and the artists name \"GALEREYA\"."));
        artworks.add(new Art("78", "Black and white photograph depicting three indigenous men", "60/272/IR_4528.0279", "Photographic prints", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a black and white photograph featuring three indigenous men standing on a dirt road. The men are carrying swags and wearing hats, two of the men are carrying billy cans and the middle one carrying a water bag. There is a green \"DAS Removals\" sticker two thirds down on the left and a white sticker with a handwritten \"10\" on the bottom right corner. On the reverse is handwritten text regarding the photograph. The photograph is mounted on a composite wooden board."));
        artworks.add(new Art("79", "Black and white photograph depicting two indigenous men with a fishing net", "60/276/IR_4528.0283", "Photographic prints", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a black and white photograph featuring two indigenous men in a river holding a net. There is a green \"DAS Removals\" sticker on the upper left and a white sticker with a handwritten \"2\" on the bottom right corner. On the reverse is handwritten text regarding the photograph. The photograph is mounted on a composite wooden board."));
        artworks.add(new Art("80", "Corroboree", "60/280/IR_4528.0287", "Replicas", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a painting depicting a corroboree with a fire in the middle and smoke blowing to the left. There is a mountain in the background and large gum trees on the left. There are two stickers on the reproduction surface and hand written text on the reverse. The reproduction is fixed to a composite wooden board."));
        artworks.add(new Art("81", "Bark painting of platypus and fish", "60/286/IR_4528.0293", "Bark paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A colour bark painting featuring two pairs of intertwined platypus positioned at the top and bottom, on the sides are two pairs of fish one yellow and one black. The background is filled with diamonds filled with cross hatching."));
        artworks.add(new Art("82", "Wall hanging print depicting a snake and two birds", "60/290/IR_4528.0297", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A yellow and black print on white fabric featuring a snake and two birds. The snake is positioned at the bottom of the print with the two birds sitting on a branch above it. The tail of the snake winds up the left side of the print, across the top and down the right side forming a boarder. The snake is patterned with black and yellow stripes. At the bottom of the print is printed the text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 11'."));
        artworks.add(new Art("83", "Wall hanging print depicting a frog and a snake", "60/291/IR_4528.0298", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A green and brown print on white fabric featuring a frog and a snake. The frog is position on a tree branch in the top half of the print with the snake wound around to the right. At the bottom of the print is printed the text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 10'."));
        artworks.add(new Art("84", "Wall hanging print depicting a kangaroo and three figures", "60/292/IR_4528.0299", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A purple and black print on white fabric featuring a kangaroo and three figures. The kangaroo is standing up-right at the bottom of the print looking backwards. Above the kangaroo are three figures sitting cross legged and holding musical instruments. At the bottom of the print is printed text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 9'."));
        artworks.add(new Art("85", "Painting of three birds", "60/301/IR_4529.0006", "Paintings", "Unknown", "Melbourne, Victoria, Australia", "Kevin J. Williams", "A colour dot painting on canvas adhered to board featuring three black emu like birds with white line detail. Surrounding the birds is brown symbolic designs and concentric circles with white dots. The background is filled with patches of yellow, purple, brown and orange dots. There is a signature in white in the bottom right corner that reads \"Kevin. williams\". On the reverse is a silver ATSIC sticker \"Asset No: VT-0058\". The painting is mounted to a black backing board and has a wooden frame."));
        artworks.add(new Art("86", "Dot painting depicting lines and boomerangs", "60/302/IR_4529.0007", "Paintings", "Unknown", "Queanbeyan, New South Wales, Australia", "Unknown", "A colour dot painting on canvas adhered to board featuring three white concentric circles horizontally across the middle with brown symbolic designs and indigenous tools surrounded in white dots. There is also four concentric circles with light brown dots and wavy brown lines. The background is grey with pink, olive, brown, yellow and green dots. On the reverse is a sticker that reads \"Asset No: N- 0152\". The painting is framed in wooden frame with gold and laminate detail."));
        artworks.add(new Art("87", "Man Dance", "60/303/IR_4529.0008", "Paintings", "Unknown", "Brisbane, Queensland, Australia", "Robin Cowburn", "A colour dot painting on canvas featuring elongated hand-like patterns in red and green with shapes of purple and yellow dots. The dots are arranged in Y shape designs throughout the painting. On the reverse is a silver ATSIC sticker that reads \"Asset No: Q- 0678\". The canvas is stapled to a wooden strainer."));
        artworks.add(new Art("88", "Dot painting of two fish in a stream", "60/304/IR_4529.0009", "Paintings", "Unknown", "Brisbane, Queensland, Australia", "Noel Doyle", "A colour dot painting on canvas featuring two raised fish. Surrounding the fish are circles which have sand, shells and rocks applied to them. The background features blue and white dots in a diagonal line patterny. There are also three raised white flowers and a black symbol in the upper left and lower right corners on a brown dot background. On the reverse is a silver Aboriginal and Torres Strait Islander Commission sticker \"Q- 0547\". The canvas is stapled to the back of a wooden strainer"));
        artworks.add(new Art("89", "Story about Richard Davey being left on an Ant Hill", "36/451/rg_36451", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour dot painting on canvas featuring four concentric circles with five black half circles with four clutches of white eggs and lizards yellow patches with black ants and one has a baby wrapped in brown blankets. On the reverse is a white sticker. The painting is under glass and has a wooden frame."));
        artworks.add(new Art("90", "Dot painting featuring six prawns", "60/310/IR_4529.0015", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Joy Crombie", "A painting on canvas featuring six prawns facing to the left. The background is painted with dots and divided into circles with orange and brown dots and wavy blue lines with blue red and yellow dots. The space in-between the wavy blue lines has a green background with blue, light blue, black and yellow dots. On the back is hand written text some of which reads \"3582\". The painting is stapled at the back to a wooden strainer."));
        artworks.add(new Art("91", "Honey Ant Dreaming", "60/311/IR_4529.0016", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Unknown", "A dot painting on canvas featuring five brown concentric circles with white dots around them. The central circle has four symbolic designs at the top, bottom, left and right. The four other circles are in the corners and surrounded by seven brown coloured honey ants, each with four black stripes. The background is black and filled with patches of brown, pink, orange, blue and yellow dots. On the back is hand written text that reads \"D8922 / CETT\". There are also two stickers one reads \"A0000270\" and an ATSIC Sticker that reads \"Asset No: NT-0524\". The canvas is stapled to the back of a wooden strainer."));
        artworks.add(new Art("92", "Print on fabric featuring a man with camp fire", "60/314/IR_4529.0019", "Prints", "Unknown", "Darwin, Northern Territory, Australia", "Bede Tungatalum", "A colour print on black fabric featuring a man in traditional dress, a fire and a sun-like image in the top right corner. On the reverse is a silver sticker from the 'ABORIGINAL DEVELOPMENT COMMISSION' with the number '8 0291'. The fabric is stretched over a wooden strainer and stapled to the back."));
        artworks.add(new Art("93", "Print featuring black lines", "60/318/IR_4529.0023", "Prints", "Unknown", "Kununurra, Kimberley, Western Australia, Australia", "Unknown", "A colour print on paper featuring a series of black horizontal lines outlined in white with a mix of yellow, orange, red and blue horizontal colouring in the background. At the bottom in pencil is \"AP / KORA / 1998\". On the reverse is a bar code sticker with the number \"F0006139\". The print is under glass has a white matt and black wooden frame."));
        artworks.add(new Art("94", "Bush Potato", "60/327/IR_4529.0032", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Jillie S. Nakamarra", "A colour dot painting on canvas featuring different black bordered by white lines. The shapes including circles, half circles, arrows, oblongs, lines and tree like branches extending from a round centre. The background is dark brown with a pattern of double dot lines in yellow, black, orange, and brown. On the reverse handwritten in pencil is \"FA 2058 / BUSH POTATO\" and in black ink \"286/97 / JULIE NAKAMARRA SPENCER / WARLUKURLANGU ARTISTS\". The canvas is stretched over a strainer and stapled to the back with a silver piece of paper pinned on the reverse with the text \"Asset No: NT-0645 / ATSIC\"."));
        artworks.add(new Art("95", "Painting of a crocodile", "60/329/IR_4529.0034", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "S Gumaiyi", "A painting on canvas featuring a crocodile facing to the left surrounded by circle patterns and wavy lines around the boarder. The crocodile is black with yellow and brown cross hatching, grey body detail and a white outline. Around the crocodile is red-brown with white, black, grey and yellow brush strokes."));
        artworks.add(new Art("96", "Painting featuring a snake with figures on it's back and footprints in the background", "60/334/IR_4529.0039", "Paintings", "Unknown", "Port Hedland, Western Australia, Australia", "Wuthoona", "A colour dot painting on canvas board featuring a yellow snake. The snake is positioned in a spiral at the centre of the painting and has figures decorated on it's body. Behind the snake are four diagonal pathways with red, black, yellow and brown foot printed lines. A brown column with several black, green and white feature sections outlined in blue runs vertically down the centre of the pathways. Between them is a background of green, red, white and blue dot segments separated by black lines. The pathways are enclosed by a thick black boarder with a brown background on the other side. On the bottom left is a signature \"Wuthoona. 93\". On the reverse is a silver sticker on the frame with the ATSIC asset number \"W-0333\". The painting has a brown wooden frame but has become separated from the frame in the top right corner."));
        artworks.add(new Art("97", "Dot painting of blue circles", "60/335/IR_4529.0040", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Janet Forrest", "A dot painting on canvas with black background and blue and white dots. The painting has a blue central circle outlined with white dots and horizontal line of white dots across the canvas. The rest of the painting consists of similar size blue circles with central white dots. On the back of the canvas is hand written text that reads \"P#10077 / Janet [Forrest---?]\" and on the strainer \"PAR0184\". The canvas is attached to a strainer and stapled to the back."));
        artworks.add(new Art("98", "Kimirrakinari", "60/336/IR_4529.0041", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Joy Crombie", "A colour painting on canvas featuring orange, yellow and white feathered brush stokes. The painting has purple dot splatters on the bottom left corner. The background is brown. The canvas is stretched over a wooden strainer and stapled to the back."));
        artworks.add(new Art("99", "Puyurru", "60/337/IR_4529.0042", "Paintings", "Unknown", "Tennant Creek, Northern Territory, Australia", "Unknown", "A colour dot painting on canvas featuring brown lines, half circles and concentric rings outlined with white dots. The concentric rings are at the centre of the painting. On either side are a thicker brown half circles shouldered by two thinner brown half circles and two vertical parallel lines. The background consists of red, yellow, blue and pink dot segment patterns. On the reverse is handwritten in blue ink information regarding the painting called \"Puyurru\" and stuck to the strainer is a blue sticker with an ATSIC number \"00291\". The painting is stretched over a strainer and stapled to the back."));
        artworks.add(new Art("100", "Painted wooden didjeridu depicting turtles and an owl", "60/355/IR_4529.0060", "Didjeridus", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A wooden didjeridu. The didjeridu is decorated over most of the body with black, brown and red bands. On the brown band is a dot design featuring turtles. Joining the bands is a black line spiralling around the body of the didjeridu. One of the black bands features a grey owl. There is a clear wax substance around the edge of one end."));
    return artworks;
    }

    public static Art getArt(String id) {
        ArrayList<Art> artworks = Art.getArtworks();
        for(final Art art : artworks) {
            if(art.getArtTitle().equals(id)) {
                return art;
            }
        }
        return null;
    }
}
