package com.example.infs3605;

import java.util.ArrayList;


public class Art {

    private String artId;
    private String artTitle;
    private String artIdentifier;
    private String artType;
    private String artDate;
    private String artRegion;
    private String artCreator;
    private String artPhysicalDescription;

    public Art(String artId, String artTitle, String artIdentifier, String artType, String artDate, String artRegion, String artCreator, String artPhysicalDescription) {
        this.artId = artId;
        this.artTitle = artTitle;
        this.artIdentifier = artIdentifier;
        this.artType = artType;
        this.artDate = artDate;
        this.artRegion = artRegion;
        this.artCreator = artCreator;
        this.artPhysicalDescription = artPhysicalDescription;
    }


    public String getArtId() {
        return artId;
    }

    public void setArtId(String artId) {
        this.artId = artId;
    }

    public String getArtTitle() {
        return artTitle;
    }

    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle;
    }

    public String getArtIdentifier() {
        return artIdentifier;
    }

    public void setArtIdentifier(String artIdentifier) {
        this.artIdentifier = artIdentifier;
    }

    public String getArtType() {
        return artType;
    }

    public void setArtType(String artType) {
        this.artType = artType;
    }

    public String getArtDate() {
        return artDate;
    }

    public void setArtDate(String artDate) {
        this.artDate = artDate;
    }

    public String getArtRegion() {
        return artRegion;
    }

    public void setArtRegion(String artRegion) {
        this.artRegion = artRegion;
    }

    public String getArtCreator() {
        return artCreator;
    }

    public void setArtCreator(String artCreator) {
        this.artCreator = artCreator;
    }

    public String getArtPhysicalDescription() {
        return artPhysicalDescription;
    }

    public void setArtPhysicalDescription(String artPhysicalDescription) {
        this.artPhysicalDescription = artPhysicalDescription;
    }

    public static ArrayList<Art> getArtworks() {
        ArrayList<Art> artworks = new ArrayList<>();
        artworks.add(new Art("1", "Carved wooden goanna with pokerwork design", "60/078/IR_4528.0087", "Wood carvings", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A carved wooden goanna. The goanna is carved from solid form with it's tail and body in a straight line. The head and tail both taper to a point. The goanna has four legs and is decorated with a pokerwork design. On the underneath handwritten in black ink is \"38 / 7-0474\"."));
        artworks.add(new Art("2", "Carved wooden bird with pokerwork design", "60/079/IR_4528.0088", "Wood carvings", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A carved wooden bird. The bird is carved from a solid form with its head and tail in a straight line. The legs are forked, protruding from beneath the body and forming the base. The body is flat with a curved surface. The tail extends upwards. The head is slightly bend to one side. The bird is decorated with a pokerwork design. On the underside handwritten in black ink is \"25 / 7-0462\".\n"));
        artworks.add(new Art("3",  "Bag with long stitch design", "60/083/IR_4528.0092", "Bags", "Unknown", "Sydney, New South Wales, Australia", "Unknown", "A bag with long stitch decoration. The bag consists of two rectangular panels of white fabric sewn together on three sides. On one of the panels is a long stitched design featuring blue lines forming diamond shapes with pink long stitched patterns in the middle. Above the design are pink long stitched crosses and circles. Below the design is a pink motif. Attached to either side of the opening is a long and narrow rectangular length of fabric to form the strap. Attached to the strap with pink cotton tape is a yellow stick it not folded in half with the number \"z0102\". Cotton threads have been sewn to the bottom of the bag on the left and right hands sides.\n"));
        artworks.add(new Art("4", "Wooden smoking pipe with a pigmented design", "60/084/IR_4528.0093", "Smoking pipes", "Unknown","Sydney, New South Wales, Australia", "Unknown", "A wooden smoking pipe. The pipe is cylindrical in shape, tapering slightly at either end. The centre of the pipe is hollowed out at one end. At the other end is attached a hollow cylindrical piece of metal. The pipe is pigmented brown and yellow with bands of white, yellow and brown cross hatchings. Attached to either end of the pipe is a piece of yellow blue tack.\n"));
        artworks.add(new Art("5", "Wooden container with a painted design depicting a bird flying over a landscape", "60/097/IR_4528.0106", "Containers", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A carved wooden coolamon. The coolamon is narrow and curved with rounded sides. The surface is pigmented brown with a bird and landscape design on the exterior. The bird is white with black outlines and dot patterning. The landscape consists of a river and trees. Attached to the interior surface is a white sticker with black handwritten text \"018/05\".\n"));
        artworks.add(new Art("6", "Wooden shield with pokerwork design", "60/100/IR_4528.0109", "Shields", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A carved wooden shield. The shield is carved from solid form, is oval in shape with a handle carved into the centre of the posterior surface. On the handle are two stickers, one a bar code sticker with the numbers \"A0000145\", and the other a red and silver sticker with the text \"PROPERTY OF / ATSIC / CRO\" and the asset number \"00144\". The anterior surface is decorated with etchings and pokerwork design featuring snakes, and landscape panels with birds and kangaroos.\n"));
        artworks.add(new Art("7", "Carving of a turtle", "60/101/IR_4528.0110", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Nawurapu Wunungmurra", "A wooden carving from one piece of cylindrical wood featuring a turtle with a long neck opposite a piece of wood. The turtle is pigmented black with the shell decorated with diamond and cross hatch design in brown, yellow and white. On the other side of the turtle on the piece of wood is the same diamond and cross hatch patterns. Underneath the base is handwritten text that reads 'C-5735', and a silver ATSIC sticker with the same number.\n"));
        artworks.add(new Art("8", "Beaded necklace strung with seeds", "60/102/IR_4528.0111", "Necklaces", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A beaded necklace. The necklace is made from seeds strung together on a thread. The seeds are oval in shaped with a reddish brown colouring."));
        artworks.add(new Art("9", "Necklace strung with small seed pods", "60/103/IR_4528.0112", "Necklaces", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A necklace. The necklace is made from small seed pods strung together on a blue cotton thread. The pods are hollow and shaped like small bowls. The pods are strung together based to head slightly overlapping each other.\n"));
        artworks.add(new Art("10", "Wooden carving of an unknown animal", "60/106/IR_4528.0115", "Wood carvings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A wooden carving of an animal. The animal is carved from light coloured wood, is round in shape with four legs and a broad tail tapering to a point. The head of the animal tapers downwards. The animal is decorated with a pokerwork design.\n"));
        artworks.add(new Art("11", "Wooden carving of four birds on a branch with pokerwork design", "60/108/IR_4528.0117", "Wood carvings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "The birds and branch are carved from a solid form. The branch is straight and narrow with rounded ends. The birds have oval shaped bodies with elongated necks and rounded heads tapering to the beak. Pairs of birds are positioned on either end of the branch facing each other but with their heads slightly turned in an opposing direction. The birds have been decorated with a pokerwork design.\n"));
        artworks.add(new Art("12", "Didjeridu with burned design of animals", "60/112/IR_4528.0121", "Didjeridu", "Unknown", "Alice Springs, Northern Territory, Australia", "Unknown", "A didjeridu with a burned design of a kangaroo, bird and an emu. The animal motifs are filled in with linear and curved designs and outlined with dots. Both the ends are painted black with rows of dots in white, one end also has more rows of dots in red, brown and yellow. There is a label adhered to the didjeridu which has the text \"EO10\".\n"));
        artworks.add(new Art("13", "Bird", "60/115/IR_4528.0124", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A carved wooden bird. The bird is carved from solid form standing upright on a circular base. The base tapers into the legs of the bird. The body is cylindrical with the tail tapering downwards adjacent to the base. The bird has a long neck that curves over at the head. The head is rounded, has a crest and tapers to the beak which reaches to the body. The bird is pigmented black, with brown, white and yellow cross hatched patterns on the body and tail. The base is pigmented brown. On the underside of the base is a sticker from the 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION' with the ATSIC asset number 'C-5736'. Also on the base handwritten in blue ink is 'C-5736 / ATSIC'.\n"));
        artworks.add(new Art("14", "Carved Shield", "60/116/IR_4528.0125", "Shields", "Unknown", "Kununurra, Kimberley, Western Australia, Australia", "Unknown", "A shield pigmented black carved in an oval with a convex back and flat front surface. A handle has been cut into the convex back. A carved fine zigzag line is used to create designs of lines, diamonds, semicircles and leaf-type shapes. There are also two bird motifs on the front surface. A picture hook has been screwed into the front surface and a loop of metal wire attached. There is a sticky label attached to the front surface with text that reads \"KNA - 04\".\n"));
        artworks.add(new Art("15", "Hollow log with painted decoration", "60/117/IR_4528.0126", "Ceremonial objects", "Unknown", "Brisbane, Queensland, Australia", "Unknown", "A hollow log pigmented on the outside featuring birds and goannas on a brown background with black, yellow and white lines and cross hatching separated by black lines with yellow and white dots. The ends of the log are split. There is a piece of paper at on end that reads \"No: 39\".\n"));
        artworks.add(new Art("16", "Fibre broom", "60/118/IR_4528.0127", "Brooms", "Unknown", "Brisbane, Queensland, Australia", "Unknown", "A broom featuring long thin straight fibres gathered together. At one end the fibres are platted and spiral around the gathered fibres. The is a tag attached to platted fibres that reads \"No. 42\".\n"));
        artworks.add(new Art("17", "Carved figure with miniature spear and spearthrower", "62/227/rg_62227", "Wood carvings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Unknown", "A carved human figure with spear and spearthrower. There is black hair attached to the head and the figure is pigmented with brown, white and black colours.\n"));
        artworks.add(new Art("18", "Carved wooden shield", "60/124/IR_4528.0131", "Shields", "Unknown", "Derby, Western Australia, Australia", "Unknown", "A carved and painted wooden shield. The shield is an elongated oval shape with a raised inset handle in the centre on one side. The side with the handle has been incised with a design of leaves, kangaroos, birds and a snake with a textured surface, picked out in yellow over a brown background. The other side of the shield is similarly incised with a design that features a snake surrounded by scalloped shapes. The edges of the shield are worn and chipped in places.\n"));
        artworks.add(new Art("19", "Carving of a female figure with grass skirt", "60/125/IR_4528.0132", "Wood carvings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Jack K. Kaiwulan", "A wooden carving featuring a female figure with her head facing to the left. The figure is pigmented in black, with brown lines and white dot details on the face and chest. The figure is wearing a brown grass skirt and is standing on a brown base which is oval shaped with pointed ends. ATSIC 'Asset No: C - 0683'.\n"));
        artworks.add(new Art("20", "Carving of a snake on a log", "60/126/IR_4528.0133", "Wood carvings", "Unknown", "Bourke, New South Wales, Australia", "Unknown", "A carved wooden snake wrapped around a wooden stick. The stick has a rough texture with yellow and red smudging covered by white and yellow designs. The snake is covered with black paint and has designs of spots and lines on the upper section.\n"));
        artworks.add(new Art("21", "Model bark canoe", "60/127/IR_4528.0134", "Small scale models", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A model canoe made of painted bark and grass twine. The canoe is made of a single sheet of bark folded over and sewn with twine. Each end narrows into a rounded point. The exterior of the canoe is painted in stripes and dots of white, yellow and red brown. The paint is worn in places.\n"));
        artworks.add(new Art("22", "Rug with decorative pattern", "60/129/IR_4528.0136", "Rugs", "Unknown", "Adelaide, South Australia, Australia", "Nyukana (Daisy) Baker", "A rectangular shaped rug featuring woollen strands woven together with a white cotton backing. The rug is brown with orange, red, yellow and white wavy designs surrounding a central concentric circle.\n"));
        artworks.add(new Art("23", "Spearthrower", "60/130/IR_4528.0137", "Spearthrowers", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden spear thrower with curved sides that taper to a thin end with carved rounded handle. There is orange sting wrapped around the handle. At the other end is a sharpened wooden peg which is attached with natural sting fibres which is coming loose.\n"));
        artworks.add(new Art("24", "Boomerang", "60/131/IR_4528.0138", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "An asymmetrical boomerang featuring one piece of wood with a large crack from the middle to the short arm end. There has been a whole piece broken off the inner middle which has been glued bak in place.\n"));
        artworks.add(new Art("25", "Boomerang with kangaroo pokerwork", "60/132/IR_4528.0139", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang with pokerwork featuring a kangaroo or wallaby with grass either side and three black bands at either end. On the other side is pokerwork initials which reads \"MM / Carr River\". There is also hand written text that reads \"AF119\" and a white sticker that reads \"LILLIE - PILLIE\".\n"));
        artworks.add(new Art("26", "Boomerang featuring a Koala design", "60/133/IR_4528.0140", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang with pokerwork featuring a koala in a tree with grass either side. There are four plain bands and two bands with lines at each end. On the flat side is pokerwork text that reads \"MM\". There is also handwritten text that reads \"AF118\" and two stickers.\n"));
        artworks.add(new Art("27", "Boomerang painted with grub design", "60/139/IR_4528.0146", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented red-brown with three black circles, each with a white grub with red head pictured inside the circle. The background is filled with white, black, yellow and red dots. On the flat side is pokerwork that reads \"WEMBA / WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 3 of 4\".\n"));
        artworks.add(new Art("28", "Boomerang painted with black oval design", "60/140/IR_4528.0147", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented red-brown with black ovals and circles surrounded by white, yellow, red and black dots and is varnished. On the flat side is pokerwork that reads \"WEMBA WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 4 of 4\".\n"));
        artworks.add(new Art("29", "Boomerang with five concentric circle dot designs", "60/141/IR_4528.0148", "Boomerangs", "Unknown", "Melbourne, Victoria, Australia", "Unknown", "A wooden boomerang pigmented with brown ends and black middle with a dot design featuring five concentric circles painted with white, yellow and brown dots. On the flat side is pokerwork that reads \"WEMBA WEMBA / TRIBE\". There is yellow piece of paper stuck to the back which reads \"ATSIC / 2 of 4\".\n"));
        artworks.add(new Art("30", "Carved wooden spearthrower", "60/142/IR_4528.0149", "Spearthrowers", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A carved wooden spear thrower. The spear thrower is long and curved. It tapers to a point at one end and has a carved handle at the other. The handle is oval is shape. At each end is coiled a piece of wire. The spear thrower has been damaged with a section of the wood broken off on one side and reattached with clear tape. On the exterior surface is a silver sticker from the \"ABORIGINAL DEVELOPMENT / COMMISSION\" with the ADC asset number \"5 0205\".\n"));
        artworks.add(new Art("31", "Coiled woven shallow basket with hanging hook", "60/143/IR_4528.0150", "Baskets", "Unknown", "Adelaide, South Australia, Australia", "Ellen Trevorrow", "A coiled woven basket. The basket is made from grass using a coiled basketry technique. The basket is shallow and circular with a wide flat base and straight sides. Attached to the exterior of the base is a triangle hanging hook.\n"));
        artworks.add(new Art("32", "Ceramic urn decorated with six grey figures", "60/144/IR_4528.0151", "Urns", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A ceramic urn. The urn is cylindrical and tapers to a flat base. The top of the urn tapers to a rounded lip. The urn has a brown red colouring and it decorated with six grey figures that are smooth to touch. On the base is a signature.\n"));
        artworks.add(new Art("33", "Woven fish scoop - coiled woven cone shaped basket with hanging hook", "60/145/IR_4528.0152", "Fish traps", "Unknown", "Adelaide, South Australia, Australia", "Ellen Trevorrow", "Woven fish scoop, made from rushes (Cyperus spp.) using a type of coiled basketry technique. The scoop is constructed by curling a circular matt at one end to form a cone shape. The curled edges have been intertwined with the weave to secure them together. Attached to one of the sides is a triangular hanging hook.\n"));
        artworks.add(new Art("34", "Dancing headdress", "60/147/IR_4528.0154", "Headdresses", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A conical headdress made of bark with the exterior wrapped in handmade twine in browns with a painted decoration of a vertical stripe of red surrounded by two vertical stripes of white. The tip of the cone has a cylindrical piece of wood inserted into it, wrapped in white-painted twine and with a tassel of natural coloured feathers at the very top.\n"));
        artworks.add(new Art("35", "Mimi spirits and Namarodo spirits", "60/148/IR_4528.0155", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Thompson Ngainmirra", "A colour bark painting featuring an x-ray kangaroo with a goanna at the top and a linear figure and two spears at the bottom. The bark is pigmented brown with white line and cross hatch detail. At the top and bottom are cylindrical wooden sticks bound to the bark with natural fibres though holes. On the reverse is a wooden block and two pieces of paper, one of which starts with \"ARTIST: THOMPSON NGAINMIRRA / ....\". There is also a silver sticker which has been crossed out.\n"));
        artworks.add(new Art("36", "Bark painting featuring two fish", "60/149/IR_4528.0156", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Nguleingulei Muramura", "A colour bark painting featuring two fish, the top one with fins, pigmented brown with rectangular patches of white and orange brown dots. The bark is pigmented with a black background with brown border. The ends of the bark are clamped with two pieced of wood that are bound with sting at the ends.\n"));
        artworks.add(new Art("37", "Bark painting depicting two water goannas", "60/150/IR_4528.0157", "Bark paintings", "Unknown", "Adelaide, South Australia, Australia", "Nguleingulei Muramura", "A colour bark painting featuring two x-ray goanna pigmented white with brown line patterns on a brown background. The ends of the bark cylindrical pieces of wood bound with string through four holes. On the reverse of the bark is the number \"79\" and a piece of paper some of which reads \"Two water Goannas - burral / by Dick Ngulayngulay / Murumuru...\"\n"));
        artworks.add(new Art("38", "Painting of two crabs", "60/166/IR_4528.0173", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Gnowerran", "A colour painting on bark featuring two brown crabs. The crabs are multicoloured with cross hatched line markings on their backs. The crabs are facing each other and divided by a yellow band patterned with brown and yellow dots. Within the yellow band are two brown circular shapes outlined and with yellow line markings. The background consists of black, white and brown cross hatchings. On the bottom right corner is a signature \"GNOWERAN\". The painting is under glass with a black metal frame.\n"));
        artworks.add(new Art("39", "Wooden container with dot painting on the rounded side mounted and framed", "60/153/IR_4528.0160", "Containers", "Unknown", "Adelaide, South Australia, Australia", "Molly Nungurrayi", "A painted wooden coolamon featuring three brown concentric circles surrounded by brown half circles with white dots. The background is black filled with grey, yellow and red dot patches. The coolamon is block mounted to a hessian board and framed with a wooden frame. The back of the frame has a white piece of paper that reads \"Artist: Molly Nungurrayi / Tribe: Warlpiri / Site: Yarrankanyi / Womens Dreaming / ...\". There is also two stickers one reads \"ABORIGINAL DEVELOPMENT / COMMISSION / \" 5 0345\".\n"));
        artworks.add(new Art("40", "Landscape painting with black ink", "60/167/IR_4528.0174", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Robert Eggington", "An black ink painting on paper of a landscape. There are two leafless trees one on the left and one on the right with their shadow falling to the left. In the background are smaller leafless trees with a dark patch of trees and shrubs across the middle with the bottom edges bleeding. There are eleven small birds in the sky and the foreground is filed with a wash technique.\n"));
        artworks.add(new Art("41", "Dot painting of a snake surrounding a concentric circle", "60/168/IR_4528.0175", "Paintings", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A colour dot painting on canvas featuring a snake. The snake is circling anti-clockwise towards a series of brown concentric circles at the centre of the painting. The snake is patterned with yellow, white and black dots and outlined by white dots. The background is black with brown dots and yellow dot flowers with white centres. The painting is stretched over a strainer and stapled to the back.\n"));
        artworks.add(new Art("42", "Dot painting of three platypus", "60/177/IR_4528.0184", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "A Sparrow", "A colour dot painting on canvas featuring three platypus painted in black with white and yellow markings on a brown background of yellow, white, red and varying browns dot coloured lines. A signature on the bottom right reads 'A. SPARROW'. On the reverse side printed text reads 'Fredrix /... / Quality Artists Canvas Panel / ...'.\n"));
        artworks.add(new Art("43", "Dot painting of two artefacts", "60/179/IR_4528.0186", "Paintings", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A brown and yellow dot painting on canvas board featuring stylised pictures two artefacts, one shaped like a large oblong and the other a narrow figure with blunt pointed ends. The painting is under glass and has a white matt with a brown wooden frame.\n"));
        artworks.add(new Art("44", "Painting of two emus within a circle", "60/181/IR_4528.0188", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "Mr Mark J. Knight", "A colour painting on board displaying an x-ray design of the skeletal and digestive features of two emus enclosed within a black circle outlined with brown dots and with a series of emu footprints circling clockwise on the inner rim of the circle. On the reverse is the name of the artist \"Mark John Knight\" and the paintings title \"Emus\". The painting has a gold and brown wooden frame.\n"));
        artworks.add(new Art("45", "Dot painting of an x-ray kangaroo", "60/182/IR_4528.0189", "Paintings", "Unknown", "Katherine, Northern Territory, Australia", "Unknown", "A colour dot painting on canvas board featuring an x-ray design of a kangaroo looking to its back and surrounded by a serious of different coloured dot patterns and animal footprints. The painting is under glass and has a white matt with a brown wooden frame.\n"));
        artworks.add(new Art("46", "Painting of a man sitting holding flowers with a background of dot painting", "60/184/IR_4528.0191", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A painting on wood of an indigenous man holding flowers sitting on the sand. The image of the man is surrounded by a dot design with four concentric circles in the corners. The dots are painted in white, off white, yellow and pink. There is a white sticker on the frame with text \"ATSIC P.A 9000194\". On the reverse is hand written initials \"B.D\". The painting is framed by a wooden frame painted black.\n"));
        artworks.add(new Art("47", "Another Story", "60/191/IR_4528.0198", "Prints", "Unknown", "Perth, Western Australia, Australia", "Sally Morgan", "A colour print on paper featuring many black figures below a house with a picket fence. The print is titled 'Another Story'', and signed 'Sally Morgan' with the edition number 84/95'.\n"));
        artworks.add(new Art("48", "Narlgu Dreaming", "60/193/IR_4528.0200", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Alan Egan", "A coloured dot painting on canvas board displaying an arrangement of different features including concentric circles, curving lines and thin narrow rods with pointed ends all forming a rectangular boarder around a large central feature that is outlined in white dots and then reproduced to form the cream, yellow, green, and brown dotted line patterns in the background. On the reverse is the artists name \"ALAN EGAN\", the title \"NARLGU DREAMING\" and handwritten text \"Gascoy[n?]e Yamatji / Alan. Egan\" with the ATSIC asset number \"CA-8\". The canvas is stretch over a wooden strainer and has a brown wooden frame.\n"));
        artworks.add(new Art("49", "Dot painting with central concentric circles and wavy yellow dot lines", "60/194/IR_4528.0201", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Long Jack Phillipus Tjakamarra", "A coloured dot painting on black canvas board featuring a series of yellow and brown dotted curving lines, some with white tuffs on their ends, amongst a background of varying coloured dot patterned areas with brown dot feature patterns running diagonally from each corner to the yellow and brown dotted concentric circles in the centre. On the reverse is handwritten in pencil 'Phyllis'. The canvas is stretched over a wooden strainer and stapled to the edges.\n"));
        artworks.add(new Art("50", "Painting of a crocodile and fish around a circle", "60/198/IR_4528.0205", "Paintings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Ngalawurr", "A painting on canvas board of a central circle surrounded by a crocodile and a fish. There is a cross hatched background in brown, yellow, black and white. The painting is signed \"Ngalawurr\". The painting is unframed.\n"));
        artworks.add(new Art("51", "Painting featuring four figures sitting in the grass", "60/203/IR_4528.0210", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "M Palmer", "An oil painting on canvas board featuring four indigenous men sitting on the ground the one on the left holding a white object and pointing to the ground. There is a wooden pole painted on the right of the painting and a bush with yellow flowers on the left. There are two stamps on the back. The painting is framed in a wooden frame.\n"));
        artworks.add(new Art("52", "Bark painting of a Kangaroo", "60/204/IR_4528.0211", "Bark paintings", "Unknown", "Perth, Western Australia, Australia", "Mijau Mijau", "A colour painting on bark featuring a brown kangaroo vertically positioned with white cross hatched line markings on it's face, legs and stomach and straight line markings elsewhere. On the reverse of the painting in black handwritten ink is \"Mijau Mijau\" and a label that reads \"DREAMING TIME KANGAROO. JIRITJA MOIETY. / Painted by Mijau-Mijau. / Croker Island.\"\n"));
        artworks.add(new Art("53", "Brolga Life", "60/205/IR_4528.0212", "Print", "Unknown", "Townsville, Queensland, Australia", "Joseph A. Cummins", "A black print on white paper featuring a central bird like image with white line markings emerging from the bottom and surrounded by various animal such as a crocodile, turtles, fish, frogs, other birds and insects, with two human figures to the left and scattered vegetation throughout. At the bottom is the series number \"2/50\", the title \"BROLGA LIFE AROUND WATER HOLE\" and the artists name \"Joseph. A. Cummins\". The print is under perspex, has a black matt and a dark brown wooden frame.\n"));
        artworks.add(new Art("54", "Landscape painting of mountains and grass trees", "60/210/IR_4528.0217", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Unknown", "A painting on board featuring three mountains in the background with two birds flying in the orange and pink sky above. In the landscape below is an emu in the middle foreground with a grass tree to its left and another grass tree to the far right. There are also two leafless trees on the left side and three on the right The painting is under glass with a black mat and wooden frame with gold inner edge.\n"));
        artworks.add(new Art("55", "Painting of a snake with nine black circles and two hand prints", "60/211/IR_4528.0218", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Anthony D. Chambers", "A painting on canvas board featuring a snake wrapped around nine black circles. There are two black hand prints in the bottom left and right corners with blown paint in red, white, and yellow around the outside of the hands. The background is made up of segments of white, red and yellow dots and around the outside of the snake is red, yellow line and smaller red dots. On the back is hand written text that reads \"3MIN\". The painting is framed in wooden frame\n"));
        artworks.add(new Art("56", "Northern Quolls", "60/212/IR_4528.0219", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Chrisa Bojack", "A painting on paper featuring two quolls on branches with green leaves. The quolls are brown with white spots and the background consists of splattered paint in brown, yellow and black. In the bottom left corner is painted text that reads \"NORTHERN QUOLLS\". There is nothing on the reverse. The painting is under glass mounted to a green backing board and has a wooden frame painted black. There is a white card sticky taped to the glass with hand written text that reads \"ARTIST: Chriss Bojack\".\n"));
        artworks.add(new Art("57", "Untitled landscape painting", "60/214/IR_4528.0221", "Paintings", "Unknown", "Perth, Western Australia, Australia", "M Turner", "A colour landscape painting on board featuring a body of water and a white and brown barked leafless tree. The body of water is surrounded by red rocky outcrops and leafy vegetation. The leafless tree has birds sitting in it's branches. The background consists of a blue sky scattered with white fluffy clouds. An unrecognisable signature is in the bottom right corner. On the reverse is text handwritten in pencil \"Turner. M.\", with a white marker \"DAA CA1\" and the number \"CPA1\" is stuck to the side. The painting has a silver wooden frame with gold trim.\n"));
        artworks.add(new Art("58", "Painting of leafless trees on a salt flat", "60/215/IR_4528.0222", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Lance Tjyllyungoo", "A watercolour painting on paper featuring numerous leafless trees in a black and white barren landscape. Shadows from the trees fall to the bottom left of the picture. A signature 'TTyllyungoo' appears at the bottom right corner.\n"));
        artworks.add(new Art("59", "Painting of trees on a salt flat", "60/216/IR_4528.0223", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Lance Tjyllyungoo", "A painting on paper featuring two trees in the foreground on a salt flat. There is a row of dark dense trees in the background and light washed sky with dark clouds at the top. The painting is signed in the bottom right corner.\n"));
        artworks.add(new Art("60", "Poster with image 'Kemarre's Identity'", "60/219/IR_4528.0226", "Posters", "Unknown", "Ceduna, South Australia, Australia", "Heather S. Kemarre", "A colour dot poster on paper featuring three circles compose by white dot concentric rings and joined to each other by three parallel white dot lines all surrounded by brown horseshoe shapes with grey dot outlines, and numerous shapes in two horizontal lines, made up of brown and red lines and outlined in white dots on a background of red and brown dots patterns. At the bottom of the poster is text 'KEMARRE'S IDENTITY / This shows the community of Mbantua... ARTIST: HEATHER KEMARRE SHEARER.'. The poster is under glass has a cream coloured matt with red and black edging and a black wooden frame.\n"));
        artworks.add(new Art("61", "Dot painting", "60/220/IR_4528.0227", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Unknown", "A dot painting on canvas featuring three concentric circles horizontally across the middle, there are half circles surrounding them painted purple. There are five brown figures along the bottom and six brown figures along the top. The background is black with green, yellow and purple dots. There are two stickers on the back one reads \"PROPERTY OF / ATSIC / CRO / 00182\". The painting is under glass with white mat and wooden frame painted green / blue with white ridges.\n"));
        artworks.add(new Art("62", "Poster titled 'Ngaanyatjarra Council'", "60/223/IR_4528.0230", "Posters", "Unknown", "Perth, Western Australia, Australia", "Unknown", "A colour poster featuring a reproduction of poker work design of concentric circles and overlapping of concentric circles. There is text at the bottom that reads 'NGAANYATjARRA / COUNCIL'. There are damage marks on the sides just over the middle.\n"));
        artworks.add(new Art("63", "Painting of a portrait and snake with four concentric circles", "60/225/IR_4528.0232", "Paintings", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A colour painting on black canvas board featuring the face of a bearded indigenous man wearing a red headband with a yellow, red, white, and blue dot patterned snake in the background and concentric dot circles in each of the corners. The painting has a brown wooden frame.\n"));
        artworks.add(new Art("64", "Photograph of five men, three holding weapons", "60/229/IR_4528.0236", "Photographic prints", "Unknown", "Townsville, Queensland, Australia", "Unknown", "An enlarged reproduction of a black and white photograph, depicting five seated indigenous men. One holds a spear, one holds a boomerang and one holds and elongated object on the left hand side. On the back is a blue circular sticker on the bottom left hand side with the number \"42\". The reproduction is mounted to a backing board painted black.\n"));
        artworks.add(new Art("65", "Landscape painting featuring a dirt road", "60/233/IR_4528.0240", "Paintings", "Unknown", "Perth, Western Australia, Australia", "Greg Kelly", "A painting of a dirt road with large trees either side and mountains in the background. There is a bright yellow and orange desert with green grass in the foreground and expansive sky with scattered clouds. The painting is signed by \"GREG KELLY\" in the bottom left corner. On the back there is a sticker in the top left corner with \"RA - 47\", and hand written text with \"BA17 /...\". The painting is framed in a wooden frame.\n"));
        artworks.add(new Art("66", "Painted boomerang", "60/235/IR_4528.0242", "Boomerangs", "Unknown", "Ceduna, South Australia, Australia", "Maureen Nampajinpa", "A symmetrical wooden boomerang with a painted surface featuring a dot design with yellow footprints, a pink and purple snake and two concentric dot circles. The boomerang is mounted on a black backing board but has dislodge and slipped down on the left side. On the reverse is handwritten text \"Maureen Nampajinpa / Hudson\" and the ATSIC bar code number \"A0000137\". The boomerang is under glass and has a brown matt with a brown wooden frame.\n"));
        artworks.add(new Art("67", "Two posters of artwork", "60/243/IR_4528.0250", "Posters", "Unknown", "Ceduna, South Australia, Australia", "Heather S. Kemarre", "Two coloured posters showing printed reproductions of paintings by Heather Shearer Kemarre. One poster is titled 'ARANDA DREAMING FOR TJARPE' and shows an earth coloured scene of eight slug-like shapes pointing towards the centre of the work where there are brown and white dotted circles. The other posters is titled 'WOMEN'S DREAMING FOR YERAMPE' and shows a red and brown scene of black and red insects surrounding a cross-like design outlined in white dots and a brown border. Brown and white dotted circles sit within the cross design. Both posters have the artist signature 'H.SHEARER' visibile in the bottom right corner of the work, as well as production information printed at the bottom which includes 'Printed by Concord Printing Pty. Ltd'.\n"));
        artworks.add(new Art("68", "Silk painting of two lizards", "60/244/IR_4528.0251", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Josie Davey", "A colour painting on silk featuring two lizards, two boomerang shaped objects and a snake on an off white background with yellow and brown arc patterns. The artists signature \"Josie Davey\" is in the bottom right corner. The painting is under glass and has a yellow matt with a black wooden frame.\n"));
        artworks.add(new Art("69", "Painting of fish", "60/245/IR_4528.0252", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour painting on canvas board featuring a school of grey fish facing to the left with a blue background. The artist signature \"G. HASELDINE\" is in the bottom right corner. On the reverse is stuck a guarantee from \"TIMBER CREEK / PICTURE FRAMING\". The painting is under glass, has a grey matt and a washed blue wooden frame.\n"));
        artworks.add(new Art("70", "Painting of a crocodile, snakes and a figure", "60/247/IR_4528.0254", "Paintings", "Unknown", "Bourke, New South Wales, Australia", "F E. Carlo", "A brown, white and yellow painting on canvas with a black background featuring two figures on either side of a crocodile and a snake circling from bottom to top on the left side. The signature 'E.CARLO' is in the bottom right corner. The canvas is stretched onto a wooden stretcher.\n"));
        artworks.add(new Art("71", "Aboriginal Bush food", "60/248/IR_4528.0255", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour painting on canvas board featuring four goannas and two lizards surrounded by red, green, and orange berry like objects and white witchetty grub like animals. On the reverse it the title \"Aboriginal Bush Food\" and the artists name \"GLETYS. E. HASELDINE.\" The painting has a red metal frame.\n"));
        artworks.add(new Art("72", "Mimi, A Married Man", "60/250/IR_4528.0257", "Prints", "Unknown", "Ceduna, South Australia, Australia", "Paddy F. Wainburranga", "A print on paper of a stylised indigenous figure holding two painted sticks with birds and snakes surrounding it. The print is in brown, yellow, black colours with dot details. There is a black boarder with dots surrounding the central images. The edition number is 40/99 and has written text 'PADDY.RDAM.' at the bottom.\n"));
        artworks.add(new Art("73", "Painting of a crocodile and bird with waterlilies", "60/251/IR_4528.0258", "Paintings", "Unknown", "Nhulunbuy, Gove Peninsula, Northern Territory, Australia", "Bronwyn Wuyuwa Gellet", "A painting on canvas board of a crocodile and a bird with a central flower like design. There are two flowers in the bottom left and the top right corners of the painting, with dot painting in the lower half and cross hatch painting in the upper half. Colours used include grey, green, pink and yellow with a distinctive red boarder. The painting is framed in a wooden frame painted grey.\n"));
        artworks.add(new Art("74", "Dugong", "60/259/IR_4528.0266", "Bark paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Bede Tungatalum", "A painting on material/cloth featuring five dugongs. Four of the dugongs are white and the fifth is black. All the dugongs are patterned with line markings. The background consists of a line patterned. On the reverse is a silver sticker from the 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION' with the ATSIC asset number 'C-0981'. The canvas is stretch over a strainer and attached to a black backing board. Attached to the top of the backing board with cotton tape is a black label with white text 'Dugong / Bebe Tungatalum b1852 / ?'. The label is in a clear plastic zip lock bag.\n"));
        artworks.add(new Art("75", "Dot painting", "60/260/IR_4528.0267", "Paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Leonora Napparulla", "A colour dot painting on canvas featuring a pattern of concentric circles, and half circle shapes. In the centre are brown concentric circles with half circles around the outside circle. The top and bottom of the middle circles are circles consisting of small half circle shapes. To the left and right of the middle circle are circles consisting of large half circle shapes. On the reverse handwritten in black ink \"C-1701 / FRAME 357\". Also on the reverse is a silver sticker from the \"ABORIGINAL AND TORRES STRAIT / INSLANDER COMMISSION\" with the ATSIC asset number \"C-1701\". Attached the reverse with brown tape is a black label with white text \"Title unknown / Leonora Napparulla / ...\". The canvas is stretched over a strainer, has a backing board and a brown wooden frame.\n"));
        artworks.add(new Art("76", "Four kangaroos and an echidna", "60/267/IR_4528.0274", "Bark paintings", "Unknown", "Sydney, New South Wales, Australia", "Djawida Nadjongorle", "A colour painting on bark featuring four kangaroos and an echidna depicted in an X-ray cross hatch design. The echidna is positioned at the bottom of the painting with the four kangaroos positioned one above the other above it. The cross hatch design is in black, white, yellow and red stripes. Wooden sticks are attached to the top and bottom of the bark with string. On the reverse handwritten in black ink is 'OE.103 / ARTRED / 5/201'. Also on the reverse is adhered a piece of white paper with the text 'OENPELLI BARK PAINTINGS / ... / ARTIST DJAWIDA / ...'. In the top left corner of the paper is a silver sticker from the 'ABORIGINAL DEVELOPMENT / COMMISSION' with the number '2 0574'.\n"));
        artworks.add(new Art("77", "Kangaroo", "60/269/IR_4528.0276", "Bark paintings", "Unknown", "Sydney, New South Wales, Australia", "Jimmy Kalarriya Namarnyilk", "A colour painting on bark featuring a kangaroo with a white and brown cross hatch pattern on it's tail, hind legs, forearms and face. The kangaroo is positioned vertically with it's hind legs up against it's chest. Wooden sticks are attached to the top and bottom of the bark by string. On the reverse is attached a discoloured white piece of paper with black text under the title \"OENPELLI BARK PAINTINGS\" and the artists name \"GALEREYA\".\n"));
        artworks.add(new Art("78", "Black and white photograph depicting three indigenous men", "60/272/IR_4528.0279", "Photographic prints", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a black and white photograph featuring three indigenous men standing on a dirt road. The men are carrying swags and wearing hats, two of the men are carrying billy cans and the middle one carrying a water bag. There is a green \"DAS Removals\" sticker two thirds down on the left and a white sticker with a handwritten \"10\" on the bottom right corner. On the reverse is handwritten text regarding the photograph. The photograph is mounted on a composite wooden board.\n"));
        artworks.add(new Art("79", "Black and white photograph depicting two indigenous men with a fishing net", "60/276/IR_4528.0283", "Photographic prints", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a black and white photograph featuring two indigenous men in a river holding a net. There is a green \"DAS Removals\" sticker on the upper left and a white sticker with a handwritten \"2\" on the bottom right corner. On the reverse is handwritten text regarding the photograph. The photograph is mounted on a composite wooden board.\n"));
        artworks.add(new Art("80", "Corroboree", "60/280/IR_4528.0287", "Replicas", "Unknown", "Adelaide, South Australia, Australia", "Unknown", "A reproduction of a painting depicting a corroboree with a fire in the middle and smoke blowing to the left. There is a mountain in the background and large gum trees on the left. There are two stickers on the reproduction surface and hand written text on the reverse. The reproduction is fixed to a composite wooden board.\n"));
        artworks.add(new Art("81", "Bark painting of platypus and fish", "60/286/IR_4528.0293", "Bark paintings", "Unknown", "Canberra, Australian Capital Territory, Australia", "Unknown", "A colour bark painting featuring two pairs of intertwined platypus positioned at the top and bottom, on the sides are two pairs of fish one yellow and one black. The background is filled with diamonds filled with cross hatching.\n"));
        artworks.add(new Art("82", "Wall hanging print depicting a snake and two birds", "60/290/IR_4528.0297", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A yellow and black print on white fabric featuring a snake and two birds. The snake is positioned at the bottom of the print with the two birds sitting on a branch above it. The tail of the snake winds up the left side of the print, across the top and down the right side forming a boarder. The snake is patterned with black and yellow stripes. At the bottom of the print is printed the text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 11'.\n"));
        artworks.add(new Art("83", "Wall hanging print depicting a frog and a snake", "60/291/IR_4528.0298", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A green and brown print on white fabric featuring a frog and a snake. The frog is position on a tree branch in the top half of the print with the snake wound around to the right. At the bottom of the print is printed the text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 10'.\n"));
        artworks.add(new Art("84", "Wall hanging print depicting a kangaroo and three figures", "60/292/IR_4528.0299", "Textiles", "Unknown", "Perth, Western Australia, Australia", "Naomi Mills", "A purple and black print on white fabric featuring a kangaroo and three figures. The kangaroo is standing up-right at the bottom of the print looking backwards. Above the kangaroo are three figures sitting cross legged and holding musical instruments. At the bottom of the print is printed text 'Designed by Naomi Mills © / hand printed in Western Australia'. Wooden sticks have been stapled to either end of the fabric. The ends have been folded over and stitched to the back. On the reverse stapled to the top is a white length of cord. Also on the reverse attached to the bottom right corner is a brown sticker label with raised white text 'RA - 9'.\n"));
        artworks.add(new Art("85", "Painting of three birds", "60/301/IR_4529.0006", "Paintings", "Unknown", "Melbourne, Victoria, Australia", "Kevin J. Williams", "A colour dot painting on canvas adhered to board featuring three black emu like birds with white line detail. Surrounding the birds is brown symbolic designs and concentric circles with white dots. The background is filled with patches of yellow, purple, brown and orange dots. There is a signature in white in the bottom right corner that reads \"Kevin. williams\". On the reverse is a silver ATSIC sticker \"Asset No: VT-0058\". The painting is mounted to a black backing board and has a wooden frame.\n"));
        artworks.add(new Art("86", "Dot painting depicting lines and boomerangs", "60/302/IR_4529.0007", "Paintings", "Unknown", "Queanbeyan, New South Wales, Australia", "Unknown", "A colour dot painting on canvas adhered to board featuring three white concentric circles horizontally across the middle with brown symbolic designs and indigenous tools surrounded in white dots. There is also four concentric circles with light brown dots and wavy brown lines. The background is grey with pink, olive, brown, yellow and green dots. On the reverse is a sticker that reads \"Asset No: N- 0152\". The painting is framed in wooden frame with gold and laminate detail.\n"));
        artworks.add(new Art("87", "Man Dance", "60/303/IR_4529.0008", "Paintings", "Unknown", "Brisbane, Queensland, Australia", "Robin Cowburn", "A colour dot painting on canvas featuring elongated hand-like patterns in red and green with shapes of purple and yellow dots. The dots are arranged in Y shape designs throughout the painting. On the reverse is a silver ATSIC sticker that reads \"Asset No: Q- 0678\". The canvas is stapled to a wooden strainer.\n"));
        artworks.add(new Art("88", "Dot painting of two fish in a stream", "60/304/IR_4529.0009", "Paintings", "Unknown", "Brisbane, Queensland, Australia", "Noel Doyle", "A colour dot painting on canvas featuring two raised fish. Surrounding the fish are circles which have sand, shells and rocks applied to them. The background features blue and white dots in a diagonal line patterny. There are also three raised white flowers and a black symbol in the upper left and lower right corners on a brown dot background. On the reverse is a silver Aboriginal and Torres Strait Islander Commission sticker \"Q- 0547\". The canvas is stapled to the back of a wooden strainer.\n"));
        artworks.add(new Art("89", "Story about Richard Davey being left on an Ant Hill", "36/451/rg_36451", "Paintings", "Unknown", "Ceduna, South Australia, Australia", "Gletys E. Haseldine", "A colour dot painting on canvas featuring four concentric circles with five black half circles with four clutches of white eggs and lizards yellow patches with black ants and one has a baby wrapped in brown blankets. On the reverse is a white sticker. The painting is under glass and has a wooden frame.\n"));
        artworks.add(new Art("90", "Dot painting featuring six prawns", "60/310/IR_4529.0015", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Joy Crombie", "A painting on canvas featuring six prawns facing to the left. The background is painted with dots and divided into circles with orange and brown dots and wavy blue lines with blue red and yellow dots. The space in-between the wavy blue lines has a green background with blue, light blue, black and yellow dots. On the back is hand written text some of which reads \"3582\". The painting is stapled at the back to a wooden strainer.\n"));
        artworks.add(new Art("91", "Honey Ant Dreaming", "60/311/IR_4529.0016", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Unknown", "A dot painting on canvas featuring five brown concentric circles with white dots around them. The central circle has four symbolic designs at the top, bottom, left and right. The four other circles are in the corners and surrounded by seven brown coloured honey ants, each with four black stripes. The background is black and filled with patches of brown, pink, orange, blue and yellow dots. On the back is hand written text that reads \"D8922 / CETT\". There are also two stickers one reads \"A0000270\" and an ATSIC Sticker that reads \"Asset No: NT-0524\". The canvas is stapled to the back of a wooden strainer.\n"));
        artworks.add(new Art("92", "Print on fabric featuring a man with camp fire", "60/314/IR_4529.0019", "Prints", "Unknown", "Darwin, Northern Territory, Australia", "Bede Tungatalum", "A colour print on black fabric featuring a man in traditional dress, a fire and a sun-like image in the top right corner. On the reverse is a silver sticker from the 'ABORIGINAL DEVELOPMENT COMMISSION' with the number '8 0291'. The fabric is stretched over a wooden strainer and stapled to the back.\n"));
        artworks.add(new Art("93", "Print featuring black lines", "60/318/IR_4529.0023", "Prints", "Unknown", "Kununurra, Kimberley, Western Australia, Australia", "Unknown", "A colour print on paper featuring a series of black horizontal lines outlined in white with a mix of yellow, orange, red and blue horizontal colouring in the background. At the bottom in pencil is \"AP / KORA / 1998\". On the reverse is a bar code sticker with the number \"F0006139\". The print is under glass has a white matt and black wooden frame.\n"));
        artworks.add(new Art("94", "Bush Potato", "60/327/IR_4529.0032", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Jillie S. Nakamarra", "A colour dot painting on canvas featuring different black bordered by white lines. The shapes including circles, half circles, arrows, oblongs, lines and tree like branches extending from a round centre. The background is dark brown with a pattern of double dot lines in yellow, black, orange, and brown. On the reverse handwritten in pencil is \"FA 2058 / BUSH POTATO\" and in black ink \"286/97 / JULIE NAKAMARRA SPENCER / WARLUKURLANGU ARTISTS\". The canvas is stretched over a strainer and stapled to the back with a silver piece of paper pinned on the reverse with the text \"Asset No: NT-0645 / ATSIC\".\n"));
        artworks.add(new Art("95", "Painting of a crocodile", "60/329/IR_4529.0034", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "S Gumaiyi", "A painting on canvas featuring a crocodile facing to the left surrounded by circle patterns and wavy lines around the boarder. The crocodile is black with yellow and brown cross hatching, grey body detail and a white outline. Around the crocodile is red-brown with white, black, grey and yellow brush strokes.\n"));
        artworks.add(new Art("96", "Painting featuring a snake with figures on it's back and footprints in the background", "60/334/IR_4529.0039", "Paintings", "Unknown", "Port Hedland, Western Australia, Australia", "Wuthoona", "A colour dot painting on canvas board featuring a yellow snake. The snake is positioned in a spiral at the centre of the painting and has figures decorated on it's body. Behind the snake are four diagonal pathways with red, black, yellow and brown foot printed lines. A brown column with several black, green and white feature sections outlined in blue runs vertically down the centre of the pathways. Between them is a background of green, red, white and blue dot segments separated by black lines. The pathways are enclosed by a thick black boarder with a brown background on the other side. On the bottom left is a signature \"Wuthoona. 93\". On the reverse is a silver sticker on the frame with the ATSIC asset number \"W-0333\". The painting has a brown wooden frame but has become separated from the frame in the top right corner.\n"));
        artworks.add(new Art("97", "Dot painting of blue circles", "60/335/IR_4529.0040", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Janet Forrest", "A dot painting on canvas with black background and blue and white dots. The painting has a blue central circle outlined with white dots and horizontal line of white dots across the canvas. The rest of the painting consists of similar size blue circles with central white dots. On the back of the canvas is hand written text that reads \"P#10077 / Janet [Forrest---?]\" and on the strainer \"PAR0184\". The canvas is attached to a strainer and stapled to the back.\n"));
        artworks.add(new Art("98", "Kimirrakinari", "60/336/IR_4529.0041", "Paintings", "Unknown", "Darwin, Northern Territory, Australia", "Joy Crombie", "A colour painting on canvas featuring orange, yellow and white feathered brush stokes. The painting has purple dot splatters on the bottom left corner. The background is brown. The canvas is stretched over a wooden strainer and stapled to the back.\n"));
        artworks.add(new Art("99", "Puyurru", "60/337/IR_4529.0042", "Paintings", "Unknown", "Tennant Creek, Northern Territory, Australia", "Unknown", "A colour dot painting on canvas featuring brown lines, half circles and concentric rings outlined with white dots. The concentric rings are at the centre of the painting. On either side are a thicker brown half circles shouldered by two thinner brown half circles and two vertical parallel lines. The background consists of red, yellow, blue and pink dot segment patterns. On the reverse is handwritten in blue ink information regarding the painting called \"Puyurru\" and stuck to the strainer is a blue sticker with an ATSIC number \"00291\". The painting is stretched over a strainer and stapled to the back.\n"));
        artworks.add(new Art("100", "Painted wooden didjeridu depicting turtles and an owl", "60/355/IR_4529.0060", "Didjeridus", "Unknown", "Townsville, Queensland, Australia", "Unknown", "A wooden didjeridu. The didjeridu is decorated over most of the body with black, brown and red bands. On the brown band is a dot design featuring turtles. Joining the bands is a black line spiralling around the body of the didjeridu. One of the black bands features a grey owl. There is a clear wax substance around the edge of one end.\n"));
        artworks.add(new Art("101","Broken Journey","61/993/IR_4534.0232","Oil paintings","1990","Canberra, Australian Capital Territory, Australia","Gayle Maddington","A colour oil painting on canvas featuring three black figures on a roughly painted background of blue, grey, red, brown and pink. The painting is signed in the bottom right corner 'GAYLE MADDIGAN \"90\"'. On the reverse is hand written text that reads 'C-0290' and a white sticker label that reads 'To Gayle Maddigan / Broken Journey'. The painting is framed in a wooden frame with a wooden background.\n"));
        artworks.add(new Art("102","Desert Flower","61/955/IR_4534.0193","Acrylic paintings","1990","Canberra, Australian Capital Territory, Australia","Angkuna Tjitayi","A colour painting on paper featuring a pattern that has black, blue, orange, green and red lines. The painting is signed in the bottom right corner that reads \"Ankuna\". There is text on the reverse is handwritten text that reads \"PA 506\" and sticker with handwritten text that reads \"Ankuna / Desert Flower / ...\".\n"));
        artworks.add(new Art("103","Under the Ground I","61/931/IR_4534.0169","Paintings","1990","Canberra, Australian Capital Territory, Australia","Naomi Mills","A watercolour and collage colour painting on paper featuring an underwater landscape in three sections. On the bottom right corner is a signature 'Naomi Mills 90'. On the reverse handwritten in blue ink is 'P.A. 849 / FRAME 452' and 'ATSIC. A white sticker is attached to the reverse with handwritten text 'Naomi Mills / \"Under the Ground' II\" / ATSIC / ...' The painting is under glass, has a cream matt and a black metal frame.\n"));
        artworks.add(new Art("104","The Answer is Blowing in the Wind","61/911/IR_4534.0149","Paintings","1990","Canberra, Australian Capital Territory, Australia","Ms Treahna Hamm","A colour painting on paper featuring a border of stylised human figures surrounding pools containing clusters of semi-circular shapes on an orange background. The painting is signed on the bottom right corner \"Trehna Hamm / '90\". Adhered to the reverse of the painting are three stickers and handwritten on the backing board is \"C-0675 FRAME:115\".The painting is housed within a glazed, black metal frame. Adhered to the glass is a black text panel.\n"));
        artworks.add(new Art("105","Guardian Spirit","61/874/IR_4534.0112","Paintings","1990","Canberra, Australian Capital Territory, Australia","Judy Watson","A colour painting on paper featuring a white image against a black background.\n"));
        artworks.add(new Art("106","Flinders Ranges","61/586/IR_4533.0253","Watercolour paintings","1990","Wagga Wagga, New South Wales, Australia","Daniel Goodwin","A watercolour painting on board featuring a gum tree and beside it is a red cliff. There are mountains in the background on the right. The painting is signed 'DGOODWIN. 90 / FLINDERS. RANGERS, SA'. On the reverse is hand written text that reads 'N-0080' and two stickers with typed text that reads '0079 / FLINDERS RANGERS / DANIEL GOODWIN / ...'. .The painting is under glass, has a bone coloured mat and a wooden frame.\n"));
        artworks.add(new Art("107","Ayres Rock and the Olgas","61/563/IR_4533.0231","Watercolour paintings","1990","Wagga Wagga, New South Wales, Australia","Daniel Goodwin","A watercolour painting on board featuring a landscape lined with green trees, Uluru in the background and round boulders on the right. The painting is signed in the e bottom right corner 'D GOODWIN 90 / AYRS ROCK & MT OLGAS'. On the reverse is a silver ATSIC sticker some of which reads 'Asset No: N- 0080' The painting is under glass with cream mat and gold wooden frame.\n"));
        artworks.add(new Art("108","Water Lilies","61/269/IR_4532.0323","Watercolour paintings","1990","Brisbane, Queensland, Australia","Harold Joesph Thomas","A colour watercolour painting on paper featuring trees reflected in water which has a bird, waterlily pads and flowers on its surface. It has a removable black plaque which features the title, artist and information on the painting. On the reverse is the handwritten text 'C-0685', a framer's stamp, and the number '7858 HTH'. There is also a bar code with the number 'F0008575'. The work is under glass, and has a gold timber frame. It is on a white and brown matt.\n"));
        artworks.add(new Art("109","Burning Up","60/706/IR_4530.0181","Paintings","1990","Canberra, Australian Capital Territory, Australia","Judy Watson","A painting on canvas by Judy Watson titled 'Burning Up'. The painting features a flame-like design in red and white on a black background, flanked with film strip-like panels in black, white and yellow on either side. On the reverse side of the canvas words are handwritten 'Judy Watson / \"burning up\" / Completed Oct. 1990. / C/- 64 Agnes St. / Acacia Ridge Q. 4110. / Brisbane. 07-2770917'. There is also a silver sticker printed in blue: 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION / Asset No: C-0507 / ATSIC' and handwritten in black: 'ASSET NO: C-0507'. The top and bottom of the canvas is studded with brass eyelets.\n"));
        artworks.add(new Art("110","Dot Painting","60/591/IR_4530.0067","Paintings","1990","Alice Springs, Norther Territory, Australia","Dorothy Napangardi","A dot painting on black canvas featuring a series of white dot lines that resemble cracks. The cracks appear like markings on a surface of light brown dots. On the reverse is text \"Dorothy Napangardi / DN 2748A / Gallery Gondwana\" handwritten in black ink. The canvas is stretched over a wooden stretcher and stapled to the back.\n"));
        artworks.add(new Art("111","Jungedey","60/374/IR_4529.0079","Paintings","1990","Wagga Wagga, New South Wales, Australia","Max Conlon","A painting on canvas, featuring in the centre is a rectangular shape and is surrounded by white dots containing nine black figures. Surrounding them is seventeen circles, surrounded by leaf patterns which is surrounded by eight more black figures which are surrounded by black footprints. Around the border is a snake, echidna, lizard, emu and a kangaroo. The painting is signed on the right side.\n"));
        artworks.add(new Art("112","Mundagudda","60/373/IR_4529.0078","Paintings","1990","Wagga Wagga, New South Wales, Australia","Max Conlon","A painting on board featuring two figures around a concentric circle in the middle with six figures standing around the circle. There is dot design in the background with leaf patterns at the top and bottom surrounded by a white dot boarder. The painting is signed 'MCONION 11.90 / MUNDAGUDDA'. The painting is framed in a wooden frame.\n"));
        artworks.add(new Art("113","Storm Dreaming, Mount Wedge Station","60/371/IR_4529.0076","Paintings","1990","Canberra, Australian Capital Territory, Australia","Kitty Napaltjarri","A dot painting on canvas featuring a central concentric circle with black zigzag lines from the middle to the corners. There are four patches of oval shape dots and black symbolic designs. On the reverse is hand written text some of which reads 'Kitty Pultara Storm Dreaming - Mt Wedge Station / C-0289'. There are also three stickers on the back. The painting has a backing board and is framed in a wooden frame.\n"));
        artworks.add(new Art("114","Crocodile, turtle, fish and seal","61/559/IR_4533.0226","Acrylic paintings","1991","Mount Isa, Queensland, Australia","Duncan Roughsey","A colour dot painting on board featuring a central crocodile with a turtle, fish and seal like creature on a yellow background with white dots. The painting is signed at the bottom 'DUNCAN.RougHsey 91/'.\n"));
        artworks.add(new Art("115","Torres Strait Mask","61/267/IR_4532.0321","Paintings","1991","Cairns, Queensland, Australia","Joesph Dorante","A brown painting on paper featuring a mask with large eyes, an elongated nose and elongated ears in predominantly browns, whites and blacks. Behind the mask are weapons featuring patterns and a turtle. The painting also features white paint spatters.\n"));
        artworks.add(new Art("116","Dot Painting","61/206/IR_4532.0259","Paintings","1991","Mount Isa, Queensland, Australia","Ronald Eatts","A colour dot painting on board featuring a central column with a grey wavy line running vertically down the middle with brown plus shapes on the right and brown semi circles on the left. The column has a outline on either side by red vertical sections with grey, white and black dot markings. In each corner is a brown spirit figure. On the bottom left corner is the artists signature 'R.Eatts'. On the reverse handwritten in black ink is the number '43094010'. The painting has a brown wooden frame with gold trim.\n"));
        artworks.add(new Art("117","Dot painting featuring five figures","61/154/IR_4532.0206","Paintings","1991","Mount Isa, Queensland, Australia","Ronald Eatts","A colour painting on board featuring five figures and segments of a vine. The painting is divided into two sections by a vertical black curved line. To the left is a black figure, to the right are three white figures and one yellow figure. The figures have long curled nails. The left side is patterned by black circles outlined in yellow and depicts several limb like shape with long nails. The background is red with brown dots. The right side has three vine like branches amongst the figures. The background is brown with yellow and white dots. Centred at the bottom is a signature 'R. Eatts / 91'. On the reverse in black ink is the number '43094026' and a yellow sticker from 'BRUSH & PALETTE / PICTURE FRAMING'. The painting has a brown wooden frame with black and gold painted edging.\n"));
        artworks.add(new Art("118","Lizard and turtle like creature","61/150/IR_4532.0202","Bark paintings","1991","Mount Isa, Queensland, Australia","Duncan Roughsey","A painting on board featuring a lizard at the bottom and a turtle like creature with four black lines coming out of either side of its head at the top. They are surrounded by coloured circles of red, grey and black and the background is filled with white dots. There is a striped boarder in red, yellow and grey. On the back is a yellow sticker and had written number '43094015'. The painting is mounted to white canvas board and framed in wooden frame with gold inner edges.\n"));
        artworks.add(new Art("119","Two snakes and four fish","61/137/IR_4532.0189","Paintings","1991","Mount Isa, Queensland, Australia","Duncan Roughsey","A painting on board featuring two snakes crossed and four fish in the triangular areas created by the snakes. They are on a yellow background with white dots. There are also larger coloured dots in red, black grey and white. The boarder is detailed in red, yellow, grey and white stripes. The painting is signed at the bottom '91 DUNCAN.RougHsey'. On the back is a yellow sticker and the painting is attached to a white canvas board and framed in wooden frame with gold edges.\n"));
        artworks.add(new Art("120","Seven figures with dots and moon shapes","61/117/IR_4532.0169","Paintings","1991","Mount Isa, Queensland, Australia","Ronald Eatts","A painting on canvas board featuring seven figures. There is a central female figure with two blue lines containing concentric circles painted in white dots. The four black figures on the left are surrounded by half moons and yellow and white circles containing black dots. There are also two black figures in the bottom right corner. On the reverse is a yellow sticker and a hand written number '43094018'.\n"));
        artworks.add(new Art("121","Dot painting featuring nine brown figures","61/116/IR_4532.0168","Paintings","1991","Mount Isa, Queensland, Australia","Ronald Eatts","A colour dot painting on board featuring nine brown figures with long fingers. Five of the figures are centred in a horizontal line, with the middle figure larger than the rest. A figure appears horizontally in each of the corners. Two bands of light brown vine like branches bordered by blue lines separate the horizontal figures from the vertical ones. The background is light brown with dark brown and white dots. The signature 'R. Eatts 91' appears at the bottom to the left of centre. On the reverse is handwritten in black ink the number '43094001' and a yellow sticker from 'BRUSH & PALETTE / PICTURE FRAMING'. The painting has a brown wooden frame with black and gold painted edging.\n"));
        artworks.add(new Art("122","Paintings of five fish a figure and bush fruits","61/115/IR_4532.0167","Paintings","1991","Mount Isa, Queensland, Australia","Ronald Eatts","A dot painting on canvas board featuring five fish in the lower half, a figure on the upper right, bush fruits on upper left and dots painted in the middle top. There are also eight circles painted with white dots joined with double white dot lines. The painting is on a brown background with brown, yellow, and white dots. On the reverse is a yellow sticker and a hand written number '43094019'. The painting is framed in a wooden frame.\n"));
        artworks.add(new Art("123","Kurlama Spears and Jilamara","60/285/IR_4528.0292","Acrylic paintings","1991","Canberra, Australian Capital Territory, Australia","Maria Josette Orsto","A colour painting on canvas featuring a circle and three arrow like shapes. The circle is segmented into four quadrants and has a boarder patterned with squares. The painting has a black background. Attached to the bottom of the canvas with velcro is a black label with white text 'Kurlama Spears and Jilamara / Maria Josette Orsto b1962 / ...'. On the reverse handwritten in black text is 'C-0566 / $1200.00 1991 / FRAME 155 / Maria Josette Orsto'. Also on reverse is a silver sticker from the 'ABORIGINAL AND TORRES STRAIT / ISLANDER COMMISSION' with the ATSIC asset number 'C-0564'. The canvas is stretched over a strainer and has a black wooden frame.\n"));
        artworks.add(new Art("124","Painting of crocodile and three figures","60/255/IR_4528.0262","Paintings","1991","Adelaide, South Australia","Tony Gamarrow","A colour painting on paper featuring a crocodile and three human like figures. The crocodile is positioned vertically on it's head with the three figures surrounding him. One of the figures is positioned lying at the bottom of the painting near the crocodiles open mouth. The crocodile and the figures are yellow, patterned by white and brown line hatchings. The background is brown with white objects, including feathers, spears and clubs.\n"));
        artworks.add(new Art("125","Janganpa (Possum) Story","59/835/IR_4527.0009","Acrylic paintings","1991","Canberra, Australian Capital Territory, Australia","Johnny Possum Tjapaltjarri","A colour painting on canvas featuring a concentric circle in the centre with yellow, grey and orange lines and brown symbolic patterns on top. There are also grey and red lines. On the reverse is an ATSIC sticker that reads 'C-6290' and hand written text that reads ' ... / Frame 431'. The canvas is framed in a wooden frame with a white backing board.\n"));
        artworks.add(new Art("126","Dot painting", "61/854/IR_4534.0092","Acrylic paintings","1992","Canberra, Australian Capital Territory, Australia","Dale Huddleston","A colour painting on canvas featuring a central concentric circle surrounded by boomerangs and six thick green lines. The painting is signed in the bottom right corner 'DALE HUDDLESTON / 92'. On the reverse is handwritten text that reads 'PA608 / ?' and a white sticker. The canvas is stapled to a wooden strainer and has a red wooden frame.\n"));
        artworks.add(new Art("127","Watercolour painting of clubs and a carved head","61/845/IR_4534.0083","Watercolour paintings","1992","Canberra, Australian Capital Territory, Australia","Joseph Dorante","A watercolour painting on paper featuring a mottled background, four carved clubs and a carved stylised human head.\n"));
        artworks.add(new Art("128","Purlpurlpungka","61/783/IR_4534.0010","Acrylic paintings","1992","Kalgoorlie, Western Australia, Australia","Joy McArthur","A colour painting on canvas featuring a snake and two lizard. There is also a circle with symbolic designs on a background of pink, brown, yellow and orange dot patches. On the reverse is handwritten text \"JOY MCARTHUR / PURLPURLPUNGKU / 1992\". The painting is attached to a wooden strainer with velcro.\n"));
        artworks.add(new Art("129","A bark painting with two squids and three fish","61/047/IR_4531.0329","Bark paintings","1952","Coffs Harbour, New South Wales, Australia","Djambalula","A coloured bark painting featuring two squid like creatures surrounded by three fish. The bark is pigmented brown with black, yellow and white line and dot details. There is a border pigmented black and yellow with black, yellow and white dots. On the reverse is a sticker with the number '52' a deteriorated piece of paper and handwritten text that reads 'gambalula / ...'.\n"));
        artworks.add(new Art("130","Waterlilies, File snakes, Spiders and Water Insects","60/515/IR_4529.0212","Bark paintings","1965","Canberra, Australian Capital Territory, Australia","Unknown","A colour painting on bark featuring waterlilies, file snakes, spiders and water insects on a brown background with white, brown and light brown cross hatching. Some white pigment has flaked off creating a purple tinge. The words \"BUSH/TUCKER\" appear on the reverse in black marker.\n"));
        artworks.add(new Art("131","Bark painting of a squid and two fish","61/045/IR_4531.0327","Bark paintings","1957","Coffs Harbour, New South Wales, Australia","Djambalula","A coloured bark painting featuring a squid and two fish, which are painted with white or pink lines and with black and yellow dots on a brown background. On the reverse of the painting is a sticker with the number '57'. There is a large crack running the length of the bark.\n"));
        artworks.add(new Art("132","Bark painting of a rock cod","61/043/IR_4531.0325","Bark paintings","1960","Coffs Harbour, New South Wales, Australia","Djambalula","A colour bark painting of a fish with its mouth open, featuring black outlines with white lines on its body, and yellow, black and white dots on a brown background. On the reverse is handwritten text that reads '60' and a piece of paper with typed text some of which reads 'Jormbalula ARTIST. '.\n"));
        artworks.add(new Art("133","Bark painting of three turtles and three fish","61/046/IR_4531.0328","Bark paintings","1962","Coffs Harbour, New South Wales, Australia","Djambalula","A coloured bark painting featuring three turtles pigmented with black lines and white, yellow and black dots. There are also two fish with white lines and a yellow fish like creature with white and black dots. The background is pigmented brown with yellow line border. On the reverse is a sticker with the number '62' and a deteriorated piece of paper with information.\n"));
        artworks.add(new Art("134","Namarodo Spirit","61/822/IR_4534.0059","Bark paintings","1985","Canberra, Australian Capital Territory, Australia","Marrainmol","A colour painting on bark featuring a male figure with brown and white cross hatch markings.The figure is standing to the left. There are four wood blocks on the reverse of the bark. There are a number of codes handwritten on the back which read \"DAA 850\" and \"MARRAINMOL / MIELLI TRIBE / ESTERN [sic] ARNHEM / LAND\".\n"));
        artworks.add(new Art("135","Man with Shield","61/144/IR_4532.0196","Paintings","1970","Canberra, Australian Capital Territory, Australia","Harold J. Thomas","An oil painting on canvas of an indigenous man with an orange object with white stripes under his arm. The man is facing to the left and has a light blue painted background and is signed in the bottom left corner 'HAROLD THOMAS / MARCH \"70\"'. On the back there is hand written text on the wooden stretcher that reads 'DAA 10001 (7788)'. The painting is framed in a wooden frame painted gold.\n"));
        artworks.add(new Art("136","Portrait of an Aboriginal woman","61/832/IR_4534.0070","Paintings","1972","Canberra, Australian Capital Territory, Australia","Unknown","A colour painting on board featuring the portrait of a woman wearing a green shirt and beige brimmed hat. The paint is signed in the bottom left corner.\n"));
        artworks.add(new Art("137","Possums at Ngamarunya","61/844/IR_4534.0082","Paintings","1973","Canberra, Australian Capital Territory, Australia","Long Jack Phillipus Tjakamarra","A colour dot painting on masonite. The panting, divided into six distinct sections by varying coloured dots and the presence of circular and linear patterns. The reverse of the painting features a sheet of white paper adhered to the surface, which bears information pertaining to the painting and the artist. Handwritten on the back of the painting is 'FRAME 412 / C-6294'. The painting is mounted on a second sheet of masonite, covered with a coarse textile and housed within a timber frame.\n"));
        artworks.add(new Art("138","Landscape 22 Alice Springs","61/986/IR_4534.0225","Paintings","1975","Canberra, Australian Capital Territory, Australia","Laurie Bray","An oil painting on canvas board of a landscape featuring two red cliffs with a body of water in between and a gum tree with three trunks on the left. The painting is signed \"LAURIE BRAY\". On the reverse is handwritten text that reads \"DAA 22/2 / DAA(T) / FRAME 410 / P.A. 693\". There are also two stickers one reads \"ATSIC Art 17\" and the other reads LANDSCAPE 22 / ALICE SPRINGS /1975 / ARTIST: LAURIE BRAY\". The painting is framed in a wooden frame. There is a sticker on the bottom left of the frame that reads \"A00693\".\n"));
        artworks.add(new Art("139","Organ Pipes Finke River NT","61/884/IR_4534.0122","Paintings","1975","Canberra, Australian Capital Territory, Australia","Laurie Bray","A colour landscape oil painting on canvas board featuring a jagged rocky outcrop. On the bottom right corner is a signature 'LAURIE BRAY'. On the reverse handwritten in black ink is 'DAA / 10020 / 7.7:88' and in blue pen 'LAWRENCE BRAY / ORGAN PIPES FINKE RIVER N.T.'. Attached to the reverse with blue tack is an orange label with white text 'Artist: Laurie Bray (deceased) / ... / DAA Collection / ...'\n"));
        artworks.add(new Art("140","Bark painting depicting a stingray","61/791/IR_4534.0018","Bark paintings","1975","Canberra, Australian Capital Territory, Australia","Bob Murdubul","A painting on bark which features a stingray. The stingray has a white, black and brown cross hatch pattern on its back and white dots elsewhere. The reverse of the bark has a sheet of paper stuck to it that has the title of the painting and the artists name along with other information. There is also 'P.A.69-' in black marker on the back of the bark.\n"));
        artworks.add(new Art("141","Eagle Waiting to Kill Kangaroo", "61/226/IR_4532.0279","Bark paintings","1975","Canberra, Australian Capital Territory, Australia","David Blanasi","A painting on bark featuring an eagle. The eagle is outlined in black with a white and yellow dot pattern. The inside of the wings and the body of the eagle have a cross hatched pattern. The background consists of a similar cross hatch design and is borderd by black lines with white and yellow dots. Wooden sticks are attached to the top and bottom of the bark with string. There is a paper label on the back of the bark with text reading \"ABORIGINAL ARTS & CRAFTS PTY. LIMITED / ... / Title Eagle Waiting to Kill Kangaroo / Artist David Blanasi\".\n"));
        artworks.add(new Art("142","Dot painting of three vertical concentric circles joined by wavy black lines","60/317/IR_4529.0022","Paintings","1975","Sydney, New South Wales, Australia","Charlie T. Tjungurrayi","A colour dot painting on canvas board featuring three black concentric circles. The circles run vertically down the middle of the canvas and are joined by two straight black lines. Black wavy lines run from circle to circle on a yellow background of white, black and grey dots. On the reverse is a silver sticker with the ATSIC asset number 'N- 0544' and written in pencil 'AA 78 59 94 / CT 75635 / PT 30G111 / Charlie Taurassi Tangahai / 1975' and in black ink '* N0544'. The painting is mounted to a canvas board, is under glass and has a brown wooden frame.\n"));
        artworks.add(new Art("143","Bark Painting-Lumaluma","61/818/IR_4534.0055","Bark paintings","1976","Canberra, Australian Capital Territory, Australia","Unknown","A colour painting on bark featuring a figure with line and cross hatch design on a brown background. On the reverse of the bark is tape with handwritten text \"47 / 10047\". as well as the number \"87\" and \"[U2NS?]\" in black marker and a chalk \"7\". There is also a white patch of paint with the code \"AAB/78/7837 / 76/880/010.\" On the reverse if the casing is hand written text that reads \"DAA 10047\". There is also masking tape with the numbers \"100 / 47 / 10042 / J\" written on it.\n"));
        artworks.add(new Art("144","Bark painting depicting part of Wagilag Sisters Myth","61/233/IR_4532.0286","Bark paintings","1976","Canberra, Australian Capital Territory, Australia","Unknown","A painting on bark featuring four female figures circled by a snake. There are four goannas on the outside of the snake. The painting consists of a cross hatched design of yellow, white and brown line markings. On the reverse handwritten in black ink is the text \"Artist: [...?] / ... / Location: Maningrida / a portion of the myth of / the Wawiluk sisters...\" and the number \"10041\". Also on the reverse in a white rectangle is black text \"AAB-78-8099 / 76/880/019\".\n"));
        artworks.add(new Art("145","Framed set of twelve tiles","59/928/IR_4527.0087","Tiles","1976","Canberra, Australian Capital Territory, Australia","Thancoupie","A framed set of twelve square tiles. The tiles are made from clay and positioned in a 3 x 4 pattern to form a rectangle. The middle columns are darker in colour and have raised etchings. The tiles on the sides have raised circular features. The tiles are attached to a backing board with a black matt and black wooden frame. On the back of the backing board \"C-0323 / FRAME: 134\".\n"));
        artworks.add(new Art("146","Painting of landscape","61/987/IR_4534.0226","Paintings","1977","Canberra, Australian Capital Territory, Australia","Basil Rantji","A watercolour landscape painting on board featuring two trees on the right side with red rocks beneath them. There are green trees in the middle ground with mountains in the background that fade from red on the right to blue on the left. The painting is signed at the bottom right 'BASEL RAntji'. On the reverse is handwritten text that reads 'DAA 903 / 18.3.75'.\n"));
        artworks.add(new Art("147","Shark","60/268/IR_4528.0275","Bark paintings","1977","Sydney, New South Wales, Australia","Maw Mununggurr","A painting on bark featuring a black shark in a vertical position against a white and brown cross hatch background. The cross hatched design is separated by black lines. On the reverse handwritten in black ink is \"93 / 77/880/006 / AAB/78/7007 / 10042\".\n"));
        artworks.add(new Art("148","Lightning Snakes","60/266/IR_4528.0273","Bark paintings","1977","Sydney, New South Wales, Australia","Wakuthi Marawili","A colour painting on bark featuring a pair of snakes, birds, fish and a four legged animals. The snakes are positioned vertically facing each other down the centre of the painting. One snake is brown and the other black. Both snakes have white line markings. The rest of the animals are positioned on either side of the snakes in horizontal cross hatch segments. The four legged animals are in the top segment, are black with white line markings and positioned upside down and facing each other. The fish are in the middle, are black with white line markings, are upside down and facing each other. The birds are in the bottom segment, are black with white line markings and facing each other. There is writing in black marker on the reverse that reads \"94 10040\". There is also writing in a small white patch that reads \"AAB/78/7065 / 77/880/906\".\n"));
        artworks.add(new Art("149","Bark painting depicting a rock wallaby and two figures","62/010/IR_4534.0249","Bark paintings","1978","Canberra, Australian Capital Territory, Australia","Unknown","A colour painting on bark featuring a kangaroo and two brown figures one has white lines on a black background. On the reverse of the bark itself is the number \"AAB/78/6381\".\n"));
        artworks.add(new Art("150","Barrunindi","61/817/IR_4534.0054","Bark paintings","1978","Canberra, Australian Capital Territory, Australia","Jimmy N. Nganjmirra","A painting on bark featuring two different sized fish. The larger fish has a spear in it's back. The fish are patterned with white and brown cross hatch markings. Wooden sticks have been attached to the top and bottom of the bark with string. On the reverse handwritten in black ink is \"B258\" and \"10067\". Also on the reverse is a white rectangle with black text \"AAB/78/6828\". There is also the 84 in black marker on the bark.\n"));
        return artworks;
    }

}
